// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop View 1' | 'Desktop View 2' | 'Mobile View 1' | 'Mobile View 2' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-EKQEYEOR.js";
import "./chunks/chunk-KGAIBNJG.js";
import "./chunks/chunk-ESTNRGIO.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:about-app-carousel
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/IeJlaoWUZWu7XuvFOC7W/LKdshuimSlHFwQqMvXAu/dgJJ2Bw3u.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var AboutAppMenuFonts = getFonts(stdin_default);
var cycleOrder = ["eiSc6Uds8", "uQWSzBwca", "UEHa1o7RV", "etyDKesky"];
var serializationHash = "framer-JVkqa";
var variantClassNames = {
	eiSc6Uds8: "framer-v-1j6m4a9",
	etyDKesky: "framer-v-or21gq",
	UEHa1o7RV: "framer-v-at3eok",
	uQWSzBwca: "framer-v-1l6f2ok",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop View 1": "eiSc6Uds8",
	"Desktop View 2": "uQWSzBwca",
	"Mobile View 1": "UEHa1o7RV",
	"Mobile View 2": "etyDKesky",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "eiSc6Uds8",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "eiSc6Uds8",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const VGjPlEV_R1xjwq0b = activeVariantCallback(async (...args) => {
		setVariant("uQWSzBwca");
	});
	const uAfgtsYcC1sqzt58 = activeVariantCallback(async (...args) => {
		setVariant("eiSc6Uds8");
	});
	const VGjPlEV_Ro7zoev = activeVariantCallback(async (...args) => {
		setVariant("etyDKesky");
	});
	const uAfgtsYcCfm9fzs = activeVariantCallback(async (...args) => {
		setVariant("UEHa1o7RV");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1j6m4a9",
							className,
							classNames,
						)}
						data-framer-name={"Desktop View 1"}
						layoutDependency={layoutDependency}
						layoutId={"eiSc6Uds8"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(6px)",
							backgroundColor: "rgb(249, 248, 248)",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							WebkitBackdropFilter: "blur(6px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								etyDKesky: {
									"data-framer-name": "Mobile View 2",
								},
								UEHa1o7RV: {
									"data-framer-name": "Mobile View 1",
								},
								uQWSzBwca: {
									"data-framer-name": "Desktop View 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ImageWithFX
							suppressHydrationWarning={true}
							__framer__spring={{
								bounce: 0.2,
								damping: 37,
								delay: 0.4,
								duration: 1.2,
								durationBasedSpring: false,
								ease: [0.44, 0, 0.56, 1],
								mass: 1,
								stiffness: 150,
								type: "spring",
							}}
							__framer__styleTransformEffectEnabled={true}
							__framer__transformTargets={[
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1.3,
										skewX: 0,
										skewY: 0,
										x: 0,
										y: 0,
									},
								},
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1,
										skewX: 0,
										skewY: 0,
										x: 0,
										y: 0,
									},
								},
							]}
							__framer__transformTrigger={"onInView"}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							background={{
								alt: "A mockup of Freelio's mobile app",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1707,
								pixelWidth: 2102,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/W508S15xkXJdvalNWW9jYJSIKg.png?width=2102&height=1707",
								srcSet:
									"https://framerusercontent.com/images/W508S15xkXJdvalNWW9jYJSIKg.png?scale-down-to=512&width=2102&height=1707 512w,https://framerusercontent.com/images/W508S15xkXJdvalNWW9jYJSIKg.png?scale-down-to=1024&width=2102&height=1707 1024w,https://framerusercontent.com/images/W508S15xkXJdvalNWW9jYJSIKg.png?scale-down-to=2048&width=2102&height=1707 2048w,https://framerusercontent.com/images/W508S15xkXJdvalNWW9jYJSIKg.png?width=2102&height=1707 2102w",
							}}
							className={"framer-1coaj1g"}
							data-framer-name={"Mobile Img"}
							layoutDependency={layoutDependency}
							layoutId={"WZXt3j8_d"}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
							{...addPropertyOverrides(
								{
									etyDKesky: {
										__framer__styleTransformEffectEnabled: void 0,
									},
									uQWSzBwca: {
										__framer__styleTransformEffectEnabled: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<ImageWithFX
							suppressHydrationWarning={true}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 2710,
								pixelWidth: 3604,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?width=3604&height=2710",
								srcSet:
									"https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=512&width=3604&height=2710 512w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=1024&width=3604&height=2710 1024w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=2048&width=3604&height=2710 2048w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?width=3604&height=2710 3604w",
							}}
							className={"framer-s4vv54"}
							data-framer-name={"Web App Img"}
							layoutDependency={layoutDependency}
							layoutId={"EFnNQD0rZ"}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
							{...addPropertyOverrides(
								{
									etyDKesky: {
										__framer__spring: {
											bounce: 0.2,
											damping: 37,
											delay: 0.4,
											duration: 1.2,
											durationBasedSpring: false,
											ease: [0.44, 0, 0.56, 1],
											mass: 1,
											stiffness: 150,
											type: "spring",
										},
										__framer__styleTransformEffectEnabled: true,
										__framer__transformTargets: [
											{
												target: {
													opacity: 1,
													rotate: 0,
													rotateX: 0,
													rotateY: 0,
													scale: 1.3,
													skewX: 0,
													skewY: 0,
													x: 0,
													y: 0,
												},
											},
											{
												target: {
													opacity: 1,
													rotate: 0,
													rotateX: 0,
													rotateY: 0,
													scale: 1,
													skewX: 0,
													skewY: 0,
													x: 0,
													y: 0,
												},
											},
										],
										__framer__transformTrigger: "onInView",
										__perspectiveFX: false,
										__smartComponentFX: true,
										__targetOpacity: 1,
										background: {
											alt: "A mockup of Freelio's web app",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0,
											),
											pixelHeight: 2710,
											pixelWidth: 3604,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?width=3604&height=2710",
											srcSet:
												"https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=512&width=3604&height=2710 512w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=1024&width=3604&height=2710 1024w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=2048&width=3604&height=2710 2048w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?width=3604&height=2710 3604w",
										},
									},
									uQWSzBwca: {
										__framer__spring: {
											bounce: 0.2,
											damping: 37,
											delay: 0.4,
											duration: 1.2,
											durationBasedSpring: false,
											ease: [0.44, 0, 0.56, 1],
											mass: 1,
											stiffness: 150,
											type: "spring",
										},
										__framer__styleTransformEffectEnabled: true,
										__framer__transformTargets: [
											{
												target: {
													opacity: 1,
													rotate: 0,
													rotateX: 0,
													rotateY: 0,
													scale: 1.3,
													skewX: 0,
													skewY: 0,
													x: 0,
													y: 0,
												},
											},
											{
												target: {
													opacity: 1,
													rotate: 0,
													rotateX: 0,
													rotateY: 0,
													scale: 1,
													skewX: 0,
													skewY: 0,
													x: 0,
													y: 0,
												},
											},
										],
										__framer__transformTrigger: "onInView",
										__perspectiveFX: false,
										__smartComponentFX: true,
										__targetOpacity: 1,
										background: {
											alt: "A mockup of Freelio's web app",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0,
											),
											pixelHeight: 2710,
											pixelWidth: 3604,
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?width=3604&height=2710",
											srcSet:
												"https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=512&width=3604&height=2710 512w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=1024&width=3604&height=2710 1024w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?scale-down-to=2048&width=3604&height=2710 2048w,https://framerusercontent.com/images/pfcMvn2yqXD2Cl6VWthMkHlhaKQ.png?width=3604&height=2710 3604w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={66}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 700) -
								98
							}
							{...addPropertyOverrides(
								{
									etyDKesky: {
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 500) -
											98,
									},
									UEHa1o7RV: {
										width: "282px",
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 500) -
											98,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1bn0g85-container"}
								layoutDependency={layoutDependency}
								layoutId={"YP4VsHEND-container"}
								nodeId={"YP4VsHEND"}
								rendersWithMotion={true}
								scopeId={"dgJJ2Bw3u"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "YP4VsHEND",
									layoutId: "YP4VsHEND",
									variant: "JbQljt1V_",
									VGjPlEV_R: VGjPlEV_R1xjwq0b,
									width: "100%",
									...addPropertyOverrides(
										{
											etyDKesky: {
												uAfgtsYcC: uAfgtsYcCfm9fzs,
												variant: "x7XS7zdmH",
												VGjPlEV_R: void 0,
											},
											UEHa1o7RV: {
												style: {
													width: "100%",
												},
												VGjPlEV_R: VGjPlEV_Ro7zoev,
											},
											uQWSzBwca: {
												uAfgtsYcC: uAfgtsYcC1sqzt58,
												variant: "x7XS7zdmH",
												VGjPlEV_R: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JVkqa.framer-9fzoav, .framer-JVkqa .framer-9fzoav { display: block; }",
	".framer-JVkqa.framer-1j6m4a9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 700px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1072px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JVkqa .framer-1coaj1g { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-JVkqa .framer-s4vv54 { bottom: 0px; flex: none; left: 1048px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: -1048px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-JVkqa .framer-1bn0g85-container { bottom: 32px; flex: none; height: auto; left: 50%; position: absolute; width: auto; z-index: 1; }",
	".framer-JVkqa.framer-v-1l6f2ok .framer-1coaj1g { left: -1048px; right: 1048px; z-index: 0; }",
	".framer-JVkqa.framer-v-1l6f2ok .framer-s4vv54, .framer-JVkqa.framer-v-or21gq .framer-s4vv54 { left: 0px; right: 0px; z-index: 1; }",
	".framer-JVkqa.framer-v-at3eok.framer-1j6m4a9, .framer-JVkqa.framer-v-or21gq.framer-1j6m4a9 { height: 500px; width: 358px; }",
	".framer-JVkqa.framer-v-at3eok .framer-s4vv54 { left: 334px; right: -334px; }",
	".framer-JVkqa.framer-v-at3eok .framer-1bn0g85-container { width: 282px; }",
	".framer-JVkqa.framer-v-or21gq .framer-1coaj1g { left: -334px; right: 334px; z-index: 0; }",
];
var FramerdgJJ2Bw3u = withCSS(Component, css, "framer-JVkqa");
var stdin_default2 = FramerdgJJ2Bw3u;
FramerdgJJ2Bw3u.displayName = "About App Carousel";
FramerdgJJ2Bw3u.defaultProps = {
	height: 700,
	width: 1072,
};
addPropertyControls(FramerdgJJ2Bw3u, {
	variant: {
		options: ["eiSc6Uds8", "uQWSzBwca", "UEHa1o7RV", "etyDKesky"],
		optionTitles: [
			"Desktop View 1",
			"Desktop View 2",
			"Mobile View 1",
			"Mobile View 2",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerdgJJ2Bw3u,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AboutAppMenuFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:about-app-carousel
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "UEHa1o7RV",
	xl: "eiSc6Uds8",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutAppCarouselFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var about_app_carousel_default = ComponentWithRoot;
export { about_app_carousel_default as default };
