// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:back-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/PgQUDpvCMImOHpV5Dl1X/T5FmOIojHLzAuQ3ssyM1/RFnAbdfSq.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/gUEAcQFGkXMDzP4G6ygD/hlpJPt86PDl5gp2oJAoK/BackTrigger.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { useEffect } from "react";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var BackTrigger = ({ visible = true }) => {
	useEffect(() => {
		if (!visible) return;
		const handleBack = () => {
			if (__unframerWindow?.history?.length > 1) {
				__unframerWindow.history.back();
			} else {
				__unframerWindow.location.href = "/";
			}
		};
		const handleDocumentClick = (event) => {
			const markerElements = document.querySelectorAll(
				'[data-back-hijacker="active"]',
			);
			if (markerElements.length === 0) return;
			const clickTarget = event.target;
			for (const markerElement of markerElements) {
				let container = markerElement.parentElement;
				if (container && container.contains(clickTarget)) {
					event.preventDefault();
					event.stopPropagation();
					event.stopImmediatePropagation();
					setTimeout(handleBack, 10);
					return;
				}
				if (container && container.parentElement) {
					const upperContainer = container.parentElement;
					if (
						upperContainer.contains(clickTarget) ||
						clickTarget === upperContainer
					) {
						event.preventDefault();
						event.stopPropagation();
						event.stopImmediatePropagation();
						setTimeout(handleBack, 10);
						return;
					}
				}
			}
		};
		document.addEventListener("click", handleDocumentClick, true);
		return () =>
			document.removeEventListener("click", handleDocumentClick, true);
	}, [visible]);
	if (!visible) return null;
	return (
		<div
			suppressHydrationWarning={true}
			data-back-hijacker={"active"}
			style={{
				position: "absolute",
				top: 0,
				left: 0,
				width: "1px",
				height: "1px",
				backgroundColor: "transparent",
				zIndex: -1,
				pointerEvents: "none",
				opacity: 0,
			}}
		/>
	);
};
addPropertyControls(BackTrigger, {
	visible: {
		type: ControlType.Boolean,
		title: "Visible",
		defaultValue: true,
	},
});
BackTrigger.defaultProps = {
	visible: true,
};
var stdin_default = BackTrigger;

// /:https://framerusercontent.com/modules/Rt1THZIqLVF7X8Hjqj9D/Nmugjm8DVR38iLm43Fhe/TG8x6nADw.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"BI;Open Runde/Regular/v0",
	"BI;Open Runde/Semibold/v0",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/3exmuO07FP19gMM08TQrpXl3BGQ.woff2",
				weight: "400",
			},
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	`.framer-S3DfY .framer-styles-preset-ze9vsf:not(.rich-text-wrapper), .framer-S3DfY .framer-styles-preset-ze9vsf.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-family-bold: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 13px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className = "framer-S3DfY";

// /:https://framerusercontent.com/modules/PgQUDpvCMImOHpV5Dl1X/T5FmOIojHLzAuQ3ssyM1/RFnAbdfSq.js
var BackTriggerFonts = getFonts(stdin_default);
var enabledGestures = {
	qVc97qRC6: {
		hover: true,
	},
};
var serializationHash = "framer-QKn2d";
var variantClassNames = {
	qVc97qRC6: "framer-v-16vrg8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "qVc97qRC6",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-16vrg8",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"qVc97qRC6"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-8ce91be8-4a20-4537-9973-9f2ad4c619f7, rgb(244, 241, 238))",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						variants={{
							"qVc97qRC6-hover": {
								backgroundColor:
									"var(--token-bcc70d7d-d7d5-49ec-b477-4e5d0ae569c1, rgb(241, 235, 229))",
							},
						}}
						{...addPropertyOverrides(
							{
								"qVc97qRC6-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-8cmyyd"}
							data-framer-name={"Back Icon"}
							layoutDependency={layoutDependency}
							layoutId={"XdCAdFjRi"}
						>
							<SVG
								suppressHydrationWarning={true}
								className={"framer-om1xhl"}
								layoutDependency={layoutDependency}
								layoutId={"AzTYpX3MU"}
								opacity={1}
								requiresOverflowVisible={true}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 10" overflow="visible"><path d="M 12 5 C 12 5.276 11.776 5.5 11.5 5.5 L 1.707 5.5 L 5.354 9.146 C 5.549 9.342 5.549 9.658 5.354 9.854 C 5.159 10.049 4.842 10.049 4.646 9.854 L 0.147 5.354 C 0.053 5.26 0 5.133 0 5 C 0 4.867 0.053 4.74 0.147 4.646 L 4.646 0.147 C 4.842 -0.049 5.159 -0.049 5.354 0.147 C 5.549 0.342 5.549 0.659 5.354 0.854 L 1.707 4.5 L 6.604 4.5 L 11.5 4.5 C 11.776 4.5 12 4.724 12 5 Z" fill="var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))" stroke-width="0.6" stroke="var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))" stroke-miterlimit="10"></path></svg>'
								}
								withExternalLayout={true}
							/>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1gyxfbk"}
							data-framer-name={"Text Container"}
							layoutDependency={layoutDependency}
							layoutId={"k52hQ_LPp"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-d8g8ox"}
								data-framer-name={"Get template"}
								fonts={["Inter", "Inter-Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"elsMmcuRl"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-ze9vsf"}
										data-styles-preset={"TG8x6nADw"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
										}}
									>
										<motion.strong suppressHydrationWarning={true}>
											{"Go back"}
										</motion.strong>
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-16iv5ct"}
								data-framer-name={"Get template"}
								fonts={["Inter", "Inter-Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"hlAIhfLjb"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-ze9vsf"}
										data-styles-preset={"TG8x6nADw"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
										}}
									>
										<motion.strong suppressHydrationWarning={true}>
											{"Go back"}
										</motion.strong>
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<ComponentViewportProvider suppressHydrationWarning={true}>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1t12oyo-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"TZqVK0rtH-container"}
								nodeId={"TZqVK0rtH"}
								rendersWithMotion={true}
								scopeId={"RFnAbdfSq"}
							>
								{_jsx2(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "TZqVK0rtH",
									layoutId: "TZqVK0rtH",
									style: {
										height: "100%",
									},
									visible: true,
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QKn2d.framer-ueihb1, .framer-QKn2d .framer-ueihb1 { display: block; }",
	".framer-QKn2d.framer-16vrg8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 32px; justify-content: center; overflow: hidden; padding: 9px 12px 8px 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-QKn2d .framer-8cmyyd { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 14px); overflow: visible; position: relative; width: 14px; }",
	".framer-QKn2d .framer-om1xhl { height: 10px; left: 1px; position: absolute; top: 2px; width: 12px; }",
	".framer-QKn2d .framer-1gyxfbk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 15px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-QKn2d .framer-d8g8ox, .framer-QKn2d .framer-16iv5ct { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-QKn2d .framer-1t12oyo-container { flex: none; height: 1px; position: relative; width: auto; }",
	".framer-QKn2d.framer-v-16vrg8.hover .framer-1gyxfbk { justify-content: flex-end; }",
	...css,
];
var FramerRFnAbdfSq = withCSS(Component, css2, "framer-QKn2d");
var stdin_default2 = FramerRFnAbdfSq;
FramerRFnAbdfSq.displayName = "Back Button";
FramerRFnAbdfSq.defaultProps = {
	height: 32,
	width: 100,
};
addFonts(
	FramerRFnAbdfSq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...BackTriggerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:back-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BackButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var back_button_default = ComponentWithRoot;
export { back_button_default as default };
