// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-KZKBIQL7.js";
import { stdin_default } from "./chunks/chunk-KGAIBNJG.js";
import "./chunks/chunk-ESTNRGIO.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:banner
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/HUAy8fAPRKc91tk5zVOC/BPJVX87Nl8jO32vDx1Wo/hmZAdLJYc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/XObS6HvjfcStU3MjNPkG/xw8O010Gi8MExhwJ8Q5R/shOHdvsZO.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Runde/Semibold/v0"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
				weight: "600",
			},
		],
	},
];
var css2 = [
	'.framer-Cm0z6 .framer-styles-preset-m29x2z:not(.rich-text-wrapper), .framer-Cm0z6 .framer-styles-preset-m29x2z.rich-text-wrapper h2 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 52px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-Cm0z6 .framer-styles-preset-m29x2z:not(.rich-text-wrapper), .framer-Cm0z6 .framer-styles-preset-m29x2z.rich-text-wrapper h2 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 44px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-Cm0z6 .framer-styles-preset-m29x2z:not(.rich-text-wrapper), .framer-Cm0z6 .framer-styles-preset-m29x2z.rich-text-wrapper h2 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-Cm0z6";

// /:https://framerusercontent.com/modules/HUAy8fAPRKc91tk5zVOC/BPJVX87Nl8jO32vDx1Wo/hmZAdLJYc.js
var MainButtonFonts = getFonts(stdin_default);
var Image1WithFX = withFX(Image1);
var cycleOrder = ["uXDwXZCiw", "sdL1EYXnJ", "tyvrwbXbO"];
var serializationHash = "framer-Q3wcY";
var variantClassNames = {
	sdL1EYXnJ: "framer-v-1l1u4gg",
	tyvrwbXbO: "framer-v-138f639",
	uXDwXZCiw: "framer-v-15cdh7x",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "uXDwXZCiw",
	Mobile: "tyvrwbXbO",
	Tablet: "sdL1EYXnJ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "uXDwXZCiw",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uXDwXZCiw",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-15cdh7x",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"uXDwXZCiw"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								sdL1EYXnJ: {
									"data-framer-name": "Tablet",
								},
								tyvrwbXbO: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1v7stz7"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"orDfnsFqu"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-15m1mos"}
								data-framer-name={"Texts"}
								layoutDependency={layoutDependency}
								layoutId={"j76zITdxD"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-yz9q74"}
									data-framer-name={"Ready to get started"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"FtKXBbJcW"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											suppressHydrationWarning={true}
											className={"framer-styles-preset-m29x2z"}
											data-styles-preset={"shOHdvsZO"}
										>
											{"Ready to get started"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-rp5r2w"}
									data-framer-name={
										"Download Freelio for free. No credit card required."
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"eScfa7LSM"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-rsfkj"}
											data-styles-preset={"q2ShOlRIr"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"Download Dreelio for free. No credit card required."}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ResolveLinks
								suppressHydrationWarning={true}
								links={[
									{
										href: {
											webPageId: "XzDpWUuVS",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "XzDpWUuVS",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "XzDpWUuVS",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={55}
										y={
											(componentViewport?.y || 0) +
											(0 +
												((componentViewport?.height || 192.5) - 0 - 300.4) /
													2) +
											0 +
											245.4
										}
										{...addPropertyOverrides(
											{
												tyvrwbXbO: {
													width: `min(max(${componentViewport?.width || "100vw"}, 1px), 800px)`,
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 200) - 0 - 300.4) /
																2) +
														0 +
														245.4,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1npcicp-container"}
											layoutDependency={layoutDependency}
											layoutId={"PoG3V5Rbw-container"}
											nodeId={"PoG3V5Rbw"}
											rendersWithMotion={true}
											scopeId={"hmZAdLJYc"}
										>
											{_jsx(stdin_default, {
												suppressHydrationWarning: true,
												ektwzyaAy: "Try Freelio free",
												FHCLGB0I0:
													"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
												height: "100%",
												id: "PoG3V5Rbw",
												layoutId: "PoG3V5Rbw",
												qomMPfTNC: {
													borderColor: "rgb(227, 225, 225)",
													borderStyle: "solid",
													borderWidth: 1,
												},
												variant: matchVariant("OBWsuGAEJ"),
												width: "100%",
												yPsg9PA2x: resolvedLinks[0],
												...addPropertyOverrides(
													{
														sdL1EYXnJ: {
															yPsg9PA2x: resolvedLinks[1],
														},
														tyvrwbXbO: {
															style: {
																width: "100%",
															},
															yPsg9PA2x: resolvedLinks[2],
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
						</motion.div>
						<Image1WithFX
							suppressHydrationWarning={true}
							__framer__spring={{
								damping: 40,
								delay: 0,
								duration: 0.3,
								ease: [0.44, 0, 0.56, 1],
								mass: 1,
								stagger: 0,
								stiffness: 150,
								type: "spring",
							}}
							__framer__styleTransformEffectEnabled={true}
							__framer__transformTargets={[
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1,
										skewX: 0,
										skewY: 0,
										x: -200,
										y: 0,
									},
								},
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1,
										skewX: 0,
										skewY: 0,
										x: 0,
										y: 0,
									},
								},
							]}
							__framer__transformTrigger={"onInView"}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + -40,
								),
								pixelHeight: 1117,
								pixelWidth: 2048,
								sizes: `calc(${(componentViewport?.height || 192.5) - -68} * 1.8335)`,
								src: "https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?width=2048&height=1117",
								srcSet:
									"https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?scale-down-to=512&width=2048&height=1117 512w,https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?scale-down-to=1024&width=2048&height=1117 1024w,https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?width=2048&height=1117 2048w",
							}}
							className={"framer-1o6kmg3"}
							data-framer-name={"Cloud Left"}
							layoutDependency={layoutDependency}
							layoutId={"G1cUoNlmF"}
							{...addPropertyOverrides(
								{
									sdL1EYXnJ: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(componentViewport?.height || 192.5) -
													197.8926,
											),
											pixelHeight: 1117,
											pixelWidth: 2048,
											sizes: "372px",
											src: "https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?width=2048&height=1117",
											srcSet:
												"https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?scale-down-to=512&width=2048&height=1117 512w,https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?scale-down-to=1024&width=2048&height=1117 1024w,https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?width=2048&height=1117 2048w",
										},
									},
									tyvrwbXbO: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(componentViewport?.height || 200) -
													225,
											),
											pixelHeight: 1117,
											pixelWidth: 2048,
											sizes: "280px",
											src: "https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?width=2048&height=1117",
											srcSet:
												"https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?scale-down-to=512&width=2048&height=1117 512w,https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?scale-down-to=1024&width=2048&height=1117 1024w,https://framerusercontent.com/images/iR8Ma0AjH7EaIAPThF3xcp9l3bM.png?width=2048&height=1117 2048w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<Image1WithFX
							suppressHydrationWarning={true}
							__framer__spring={{
								damping: 40,
								delay: 0,
								duration: 0.3,
								ease: [0.44, 0, 0.56, 1],
								mass: 1,
								stagger: 0,
								stiffness: 150,
								type: "spring",
							}}
							__framer__styleTransformEffectEnabled={true}
							__framer__transformTargets={[
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1,
										skewX: 0,
										skewY: 0,
										x: 200,
										y: 0,
									},
								},
								{
									target: {
										opacity: 1,
										rotate: 0,
										rotateX: 0,
										rotateY: 0,
										scale: 1,
										skewX: 0,
										skewY: 0,
										x: 0,
										y: 0,
									},
								},
							]}
							__framer__transformTrigger={"onInView"}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							background={{
								alt: "",
								fit: "fit",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + -40,
								),
								pixelHeight: 1380,
								pixelWidth: 2531,
								positionX: "center",
								positionY: "center",
								sizes: `calc(${(componentViewport?.height || 192.5) - -68} * 1.8339)`,
								src: "https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?width=2531&height=1380",
								srcSet:
									"https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=512&width=2531&height=1380 512w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=1024&width=2531&height=1380 1024w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=2048&width=2531&height=1380 2048w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?width=2531&height=1380 2531w",
							}}
							className={"framer-1kghxmt"}
							data-framer-name={"Cloud Right"}
							layoutDependency={layoutDependency}
							layoutId={"mp5Se6w71"}
							{...addPropertyOverrides(
								{
									sdL1EYXnJ: {
										background: {
											alt: "",
											fit: "fit",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(componentViewport?.height || 192.5) -
													197.8425,
											),
											pixelHeight: 1380,
											pixelWidth: 2531,
											positionX: "center",
											positionY: "center",
											sizes: "372px",
											src: "https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?width=2531&height=1380",
											srcSet:
												"https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=512&width=2531&height=1380 512w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=1024&width=2531&height=1380 1024w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=2048&width=2531&height=1380 2048w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?width=2531&height=1380 2531w",
										},
									},
									tyvrwbXbO: {
										background: {
											alt: "",
											fit: "fit",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(componentViewport?.height || 200) -
													225,
											),
											pixelHeight: 1380,
											pixelWidth: 2531,
											positionX: "center",
											positionY: "center",
											sizes: "280px",
											src: "https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?width=2531&height=1380",
											srcSet:
												"https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=512&width=2531&height=1380 512w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=1024&width=2531&height=1380 1024w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?scale-down-to=2048&width=2531&height=1380 2048w,https://framerusercontent.com/images/qazH0744I2w9AnpfmUJIze7g.png?width=2531&height=1380 2531w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Q3wcY.framer-1b6ec55, .framer-Q3wcY .framer-1b6ec55 { display: block; }",
	".framer-Q3wcY.framer-15cdh7x { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1072px; }",
	".framer-Q3wcY .framer-1v7stz7 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; max-width: 800px; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-Q3wcY .framer-15m1mos { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Q3wcY .framer-yz9q74, .framer-Q3wcY .framer-rp5r2w { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Q3wcY .framer-1npcicp-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Q3wcY .framer-1o6kmg3 { aspect-ratio: 1.8334826483242754 / 1; bottom: -28px; flex: none; left: -280px; position: absolute; top: -40px; width: var(--framer-aspect-ratio-supported, 478px); z-index: 1; }",
	".framer-Q3wcY .framer-1kghxmt { aspect-ratio: 1.8339350180505416 / 1; bottom: -28px; flex: none; position: absolute; right: -280px; top: -40px; width: var(--framer-aspect-ratio-supported, 478px); z-index: 1; }",
	".framer-Q3wcY.framer-v-1l1u4gg.framer-15cdh7x { width: 730px; }",
	".framer-Q3wcY.framer-v-1l1u4gg .framer-1o6kmg3, .framer-Q3wcY.framer-v-1l1u4gg .framer-1kghxmt { bottom: -5px; height: var(--framer-aspect-ratio-supported, 203px); top: unset; width: 372px; }",
	".framer-Q3wcY.framer-v-138f639.framer-15cdh7x { width: 350px; }",
	".framer-Q3wcY.framer-v-138f639 .framer-1npcicp-container { width: 100%; }",
	".framer-Q3wcY.framer-v-138f639 .framer-1o6kmg3 { bottom: 72px; height: var(--framer-aspect-ratio-supported, 153px); left: -240px; top: unset; width: 280px; }",
	".framer-Q3wcY.framer-v-138f639 .framer-1kghxmt { bottom: 72px; height: var(--framer-aspect-ratio-supported, 153px); right: -240px; top: unset; width: 280px; }",
	...css2,
	...css,
];
var FramerhmZAdLJYc = withCSS(Component, css3, "framer-Q3wcY");
var stdin_default2 = FramerhmZAdLJYc;
FramerhmZAdLJYc.displayName = "Banner";
FramerhmZAdLJYc.defaultProps = {
	height: 192.5,
	width: 1072,
};
addPropertyControls(FramerhmZAdLJYc, {
	variant: {
		options: ["uXDwXZCiw", "sdL1EYXnJ", "tyvrwbXbO"],
		optionTitles: ["Desktop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerhmZAdLJYc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MainButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerhmZAdLJYc.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:banner
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BannerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var banner_default = ComponentWithRoot;
export { banner_default as default };
