// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * summary?: string // Summary
 * authorImage?: {src: string, srcSet?: string, alt?: string} // Author Image
 * authorName?: string // Author Name
 * authorPosition?: string // Author Position
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-Y2HA6WRM.js";
import { className, css, fonts } from "./chunks/chunk-7XAY5VTW.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:big-review
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/90nT4ourAgcsVSObEf1g/J9G6kmaXCr0MVbU43zOo/WiH3d3HBs.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/ygDYACq7dHKBKBmeIiRZ/6YWTdxb1tUfwkFRJiBxl/x8dgoiAmV.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Runde/Medium/v0"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/HJY4SY2JywrSZ2l1AEW9Tm9cO8.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	'.framer-RCoXy .framer-styles-preset-1xdgset:not(.rich-text-wrapper), .framer-RCoXy .framer-styles-preset-1xdgset.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 145%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-RCoXy .framer-styles-preset-1xdgset:not(.rich-text-wrapper), .framer-RCoXy .framer-styles-preset-1xdgset.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 145%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-RCoXy .framer-styles-preset-1xdgset:not(.rich-text-wrapper), .framer-RCoXy .framer-styles-preset-1xdgset.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 145%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-RCoXy";

// /:https://framerusercontent.com/modules/90nT4ourAgcsVSObEf1g/J9G6kmaXCr0MVbU43zOo/WiH3d3HBs.js
var serializationHash = "framer-kU5HM";
var variantClassNames = {
	H7IlfHCfs: "framer-v-acy3vm",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	authorImage,
	authorName,
	authorPosition,
	height,
	id,
	summary,
	width,
	...props
}) => {
	return {
		...props,
		kZeVm8RiS:
			summary ??
			props.kZeVm8RiS ??
			'"Dreelio is by far the best agency tool I have ever used"',
		lvmEg89AC: authorPosition ?? props.lvmEg89AC ?? "VP Marketing, Meta",
		myzB2Bc_h: authorName ?? props.myzB2Bc_h ?? "Martha Punla",
		UF3X6CuKx: authorImage ??
			props.UF3X6CuKx ?? {
				alt: "",
				pixelHeight: 1200,
				pixelWidth: 800,
				src: "https://framerusercontent.com/images/S9L8waMJbCRGmORsmjIGSc17h8k.png?scale-down-to=1024&width=800&height=1200",
				srcSet:
					"https://framerusercontent.com/images/S9L8waMJbCRGmORsmjIGSc17h8k.png?scale-down-to=1024&width=800&height=1200 682w,https://framerusercontent.com/images/S9L8waMJbCRGmORsmjIGSc17h8k.png?width=800&height=1200 800w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		kZeVm8RiS,
		UF3X6CuKx,
		myzB2Bc_h,
		lvmEg89AC,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "H7IlfHCfs",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-acy3vm",
							className4,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"H7IlfHCfs"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-jiwc11"}
							data-framer-name={
								'"As a fast-moving design team, we needed a tool that matched our pace. From client onboarding to getting paid, this just works \u2014 clean, fast, and beautifully built."'
							}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"jF0DkiXwt"}
							style={{
								"--framer-paragraph-spacing": "0px",
							}}
							text={kZeVm8RiS}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									suppressHydrationWarning={true}
									className={"framer-styles-preset-1xdgset"}
									data-styles-preset={"x8dgoiAmV"}
								>
									{'"Dreelio is by far the best agency tool I have ever used"'}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-tf1ppq"}
							data-framer-name={"User Info"}
							layoutDependency={layoutDependency}
							layoutId={"cxNNXTrdv"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1h42wpc"}
								data-framer-name={"Profile Image"}
								layoutDependency={layoutDependency}
								layoutId={"L6qhSpP8j"}
								style={{
									backgroundColor: "rgb(255, 255, 255)",
									borderBottomLeftRadius: 1e3,
									borderBottomRightRadius: 1e3,
									borderTopLeftRadius: 1e3,
									borderTopRightRadius: 1e3,
								}}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 484 + 0 + 0 + 2,
										),
										pixelHeight: 1200,
										pixelWidth: 800,
										sizes: "60px",
										...toResponsiveImage(UF3X6CuKx),
									}}
									className={"framer-1dxkhz1"}
									data-border={true}
									data-framer-name={"Taylor Gibson profile 1"}
									layoutDependency={layoutDependency}
									layoutId={"q5sVWhmBM"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color": "rgb(255, 255, 255)",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								/>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-treqr4"}
								data-framer-name={"Name + Position"}
								layoutDependency={layoutDependency}
								layoutId={"p86HpJX6E"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-t32abr"}
									data-framer-name={"Leah Daniel"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"XJM79OUWh"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={myzB2Bc_h}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1f5jbyr"}
											data-styles-preset={"oM4DrnKwh"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
											}}
										>
											<motion.strong suppressHydrationWarning={true}>
												{"Martha Punla"}
											</motion.strong>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-ilcvoi"}
									data-framer-name={"Design Ops Lead, teamwork."}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"PgkO9dR7q"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={lvmEg89AC}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1lpqzqx"}
											data-styles-preset={"uwmmbeA4Q"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112)))",
											}}
										>
											{"VP Marketing, Meta"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kU5HM.framer-prdi4m, .framer-kU5HM .framer-prdi4m { display: block; }",
	".framer-kU5HM.framer-acy3vm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 900px; }",
	".framer-kU5HM .framer-jiwc11 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-kU5HM .framer-tf1ppq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 400px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kU5HM .framer-1h42wpc { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 64px); overflow: hidden; position: relative; width: 64px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kU5HM .framer-1dxkhz1 { bottom: 2px; flex: none; left: 2px; position: absolute; right: 2px; top: 2px; }",
	".framer-kU5HM .framer-treqr4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kU5HM .framer-t32abr, .framer-kU5HM .framer-ilcvoi { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css3,
	...css,
	...css2,
	'.framer-kU5HM[data-border="true"]::after, .framer-kU5HM [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerWiH3d3HBs = withCSS(Component, css4, "framer-kU5HM");
var stdin_default = FramerWiH3d3HBs;
FramerWiH3d3HBs.displayName = "Big Review";
FramerWiH3d3HBs.defaultProps = {
	height: 331,
	width: 900,
};
addPropertyControls(FramerWiH3d3HBs, {
	kZeVm8RiS: {
		defaultValue: '"Dreelio is by far the best agency tool I have ever used"',
		displayTextArea: false,
		title: "Summary",
		type: ControlType.String,
	},
	UF3X6CuKx: {
		__defaultAssetReference:
			"data:framer/asset-reference,S9L8waMJbCRGmORsmjIGSc17h8k.png?originalFilename=QmSfsAMzARRmpR8z9Jh96cmEWX2eM9R2BxsrjQVgDGjwh7%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto&width=800&height=1200",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,S9L8waMJbCRGmORsmjIGSc17h8k.png?originalFilename=QmSfsAMzARRmpR8z9Jh96cmEWX2eM9R2BxsrjQVgDGjwh7%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto&width=800&height=1200",
		},
		title: "Author Image",
		type: ControlType.ResponsiveImage,
	},
	myzB2Bc_h: {
		defaultValue: "Martha Punla",
		displayTextArea: false,
		title: "Author Name",
		type: ControlType.String,
	},
	lvmEg89AC: {
		defaultValue: "VP Marketing, Meta",
		displayTextArea: false,
		title: "Author Position",
		type: ControlType.String,
	},
});
addFonts(
	FramerWiH3d3HBs,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:big-review
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BigReviewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var big_review_default = ComponentWithRoot;
export { big_review_default as default };
