// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Small' | 'Wide - Desktop' | 'Wide - Mobile' // Variant
 * title?: string // Title
 * summary?: string // Summary
 * mainImage?: {src: string, srcSet?: string, alt?: string} // Main Image
 * authorImage?: {src: string, srcSet?: string, alt?: string} // Author Image
 * authorName?: string // Author Name
 * authorPosition?: string // Author Position
 * badgeVariant?: 'Large' | 'Small' // Badge Variant
 * badge/CategoryName?: string // Badge/Category Name
 * badgeBgColor?: string // Badge Bg Color
 * badgeTextColor?: string // Badge Text Color
 * link?: string // Link
}} Props

 */
import { stdin_default } from "./chunks/chunk-ZAESKV3Q.js";
import { className, css, fonts } from "./chunks/chunk-Y2HA6WRM.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-3G7HFN4Q.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-KZKBIQL7.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-D2KCAVRQ.js";
import "./chunks/chunk-6CLJHUBU.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:blog-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Y5ErCspGAVXtbaEzwm2I/ng9kaYLmqOzRvrM2VUYo/ceNjEn0pZ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BadgeFonts = getFonts(stdin_default);
var BadgeControls = getPropertyControls(stdin_default);
var enabledGestures = {
	LZbvw34aB: {
		hover: true,
	},
	s4FWatjEv: {
		hover: true,
	},
};
var cycleOrder = ["s4FWatjEv", "LZbvw34aB", "q1SCU0o7w"];
var serializationHash = "framer-8oVXz";
var variantClassNames = {
	LZbvw34aB: "framer-v-19d003x",
	q1SCU0o7w: "framer-v-1aa92vq",
	s4FWatjEv: "framer-v-xi0zcq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0.1,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	Large: "fCuWvhC1L",
	Small: "Y6mBL48e4",
};
var humanReadableVariantMap = {
	"Wide - Desktop": "LZbvw34aB",
	"Wide - Mobile": "q1SCU0o7w",
	Small: "s4FWatjEv",
};
var getProps = ({
	authorImage,
	authorName,
	authorPosition,
	badgeBgColor,
	badgeCategoryName,
	badgeTextColor,
	badgeVariant,
	height,
	id,
	link,
	mainImage,
	summary,
	title,
	width,
	...props
}) => {
	return {
		...props,
		bYzbMW5xc:
			humanReadableEnumMap[badgeVariant] ??
			badgeVariant ??
			props.bYzbMW5xc ??
			"Y6mBL48e4",
		cCFzCovcz: link ?? props.cCFzCovcz,
		GCByEC9Fx: title ?? props.GCByEC9Fx ?? "Label",
		jnnkAQ3vy:
			badgeTextColor ??
			props.jnnkAQ3vy ??
			"var(--token-c508d2b6-c5a0-4393-9b17-65065c0b01a4, rgb(97, 74, 68))",
		MJJvWwU0l: authorImage ?? props.MJJvWwU0l,
		OY2qPhaGN: mainImage ?? props.OY2qPhaGN,
		p_ifO2pfK: badgeCategoryName ?? props.p_ifO2pfK ?? "Tools",
		pLYLm0921:
			summary ??
			props.pLYLm0921 ??
			"Use this to present your focused, personal support coaching, consulting, mentoring or therapy.",
		sJR8wjB1z: authorName ?? props.sJR8wjB1z ?? "Dyna Phils",
		UmQTZ_sR3: authorPosition ?? props.UmQTZ_sR3 ?? "Head of Marketing",
		UYzjJfLeu:
			badgeBgColor ??
			props.UYzjJfLeu ??
			"var(--token-8ce91be8-4a20-4537-9973-9f2ad4c619f7, rgb(244, 241, 238))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "s4FWatjEv",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		GCByEC9Fx,
		pLYLm0921,
		OY2qPhaGN,
		MJJvWwU0l,
		sJR8wjB1z,
		UmQTZ_sR3,
		bYzbMW5xc,
		p_ifO2pfK,
		UYzjJfLeu,
		jnnkAQ3vy,
		cCFzCovcz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "s4FWatjEv",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className4, className2, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "LZbvw34aB-hover") return true;
		if (["LZbvw34aB", "q1SCU0o7w"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={cCFzCovcz}
						motionChild={true}
						nodeId={"s4FWatjEv"}
						openInNewTab={false}
						scopeId={"ceNjEn0pZ"}
					>
						<motion.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-xi0zcq", className5, classNames)} framer-1y3hldv`}
							data-framer-name={"Small"}
							layoutDependency={layoutDependency}
							layoutId={"s4FWatjEv"}
							ref={refBinding}
							style={{
								backdropFilter: "none",
								backgroundColor: "rgba(255, 255, 255, 0)",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								WebkitBackdropFilter: "none",
								...style,
							}}
							variants={{
								"s4FWatjEv-hover": {
									backdropFilter: "none",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									WebkitBackdropFilter: "none",
								},
								LZbvw34aB: {
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(255, 255, 255, 0.7)",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
									WebkitBackdropFilter: "blur(10px)",
								},
								q1SCU0o7w: {
									backdropFilter: "none",
									backgroundColor: "rgba(255, 255, 255, 0.7)",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
									WebkitBackdropFilter: "none",
								},
							}}
							{...addPropertyOverrides(
								{
									"LZbvw34aB-hover": {
										"data-framer-name": void 0,
									},
									"s4FWatjEv-hover": {
										"data-framer-name": void 0,
									},
									LZbvw34aB: {
										"data-framer-name": "Wide - Desktop",
									},
									q1SCU0o7w: {
										"data-framer-name": "Wide - Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-u8cig0"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"VqDti_k7w"}
								style={{
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 0,
										),
										sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
										...toResponsiveImage(OY2qPhaGN),
									}}
									className={"framer-c1s8jz"}
									draggable={"false"}
									layoutDependency={layoutDependency}
									layoutId={"joU5Z8NJz"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
										scale: 1,
									}}
									variants={{
										"LZbvw34aB-hover": {
											scale: 1.15,
										},
										"s4FWatjEv-hover": {
											scale: 1.15,
										},
									}}
									{...addPropertyOverrides(
										{
											LZbvw34aB: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															8 +
															(0 +
																(((componentViewport?.height || 480) - 16) * 1 -
																	0 -
																	(((componentViewport?.height || 480) - 16) *
																		1 -
																		0) *
																		1) /
																	2),
													),
													sizes: `max((${componentViewport?.width || "100vw"} - 72px) / 2, 1px)`,
													...toResponsiveImage(OY2qPhaGN),
												},
											},
											q1SCU0o7w: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 8 + 0 + 0,
													),
													sizes: `max(${componentViewport?.width || "100vw"} - 16px, 1px)`,
													...toResponsiveImage(OY2qPhaGN),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-v571wp"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"KzN4_UsFz"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-rfsf8b"}
									data-framer-name={"Texts Contents"}
									layoutDependency={layoutDependency}
									layoutId={"pl5flIzlF"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-7gkkne"}
										data-framer-name={"Header & Texts"}
										layoutDependency={layoutDependency}
										layoutId={"UHOFS33OG"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-kpxp4c"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"KG0JZbQzg"}
											text={GCByEC9Fx}
											variants={{
												q1SCU0o7w: {
													"--extracted-a0htzi":
														"var(--token-30ace178-0286-4511-a09a-9030d0dd3619, rgb(36, 23, 18))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													LZbvw34aB: {
														children: (
															<React.Fragment>
																<motion.h3
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-s5fq9t"}
																	data-styles-preset={"jghX4nrSc"}
																>
																	{"Label"}
																</motion.h3>
															</React.Fragment>
														),
													},
													q1SCU0o7w: {
														children: (
															<React.Fragment>
																<motion.h3
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-s5fq9t"}
																	data-styles-preset={"jghX4nrSc"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-a0htzi, var(--token-30ace178-0286-4511-a09a-9030d0dd3619, rgb(36, 23, 18)))",
																	}}
																>
																	{"Label"}
																</motion.h3>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													suppressHydrationWarning={true}
													className={"framer-styles-preset-vbmqcd"}
													data-styles-preset={"WGKa97OVa"}
												>
													{"Label"}
												</motion.h6>
											</React.Fragment>
										</RichText>
										{isDisplayed() && (
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-21sj8d"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"I0EYs9IFt"}
												text={pLYLm0921}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-rsfkj"}
														data-styles-preset={"q2ShOlRIr"}
													>
														{
															"Use this to present your focused, personal support coaching, consulting, mentoring or therapy."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										)}
									</motion.div>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={34}
										y={(componentViewport?.y || 0) + 0 + 282 + 0 + 0 + 0}
										{...addPropertyOverrides(
											{
												LZbvw34aB: {
													y:
														(componentViewport?.y || 0) +
														8 +
														28 +
														(0 +
															0 +
															((((componentViewport?.height || 480) - 16) * 1 -
																56 -
																482) /
																1) *
																0) +
														0 +
														0,
												},
												q1SCU0o7w: {
													y:
														(componentViewport?.y || 0) +
														8 +
														223 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-15h42sa-container"}
											layoutDependency={layoutDependency}
											layoutId={"UE7rmNyZO-container"}
											nodeId={"UE7rmNyZO"}
											rendersWithMotion={true}
											scopeId={"ceNjEn0pZ"}
										>
											{_jsx(stdin_default, {
												suppressHydrationWarning: true,
												cRZkWhGy9: jnnkAQ3vy,
												height: "100%",
												id: "UE7rmNyZO",
												klJrZSsm3: UYzjJfLeu,
												layoutId: "UE7rmNyZO",
												variant: bYzbMW5xc,
												width: "100%",
												XQBi6J5Qe: p_ifO2pfK,
												...addPropertyOverrides(
													{
														LZbvw34aB: {
															cRZkWhGy9:
																"var(--token-d637c2eb-4179-4d4c-859c-b60c3c740338, rgb(255, 255, 255))",
															klJrZSsm3:
																"var(--token-c508d2b6-c5a0-4393-9b17-65065c0b01a4, rgb(97, 74, 68))",
															variant: "fCuWvhC1L",
															XQBi6J5Qe: "Must Read",
														},
														q1SCU0o7w: {
															cRZkWhGy9:
																"var(--token-d637c2eb-4179-4d4c-859c-b60c3c740338, rgb(255, 255, 255))",
															klJrZSsm3:
																"var(--token-c508d2b6-c5a0-4393-9b17-65065c0b01a4, rgb(97, 74, 68))",
															variant: "Y6mBL48e4",
															XQBi6J5Qe: "Must Read",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								{isDisplayed() && (
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-cxem4"}
										data-framer-name={"Author Info"}
										layoutDependency={layoutDependency}
										layoutId={"dCnirqzqJ"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1prulzd"}
											data-framer-name={"Texts"}
											layoutDependency={layoutDependency}
											layoutId={"snuyIo8ff"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-93ve88"}
												data-framer-name={"Written by Sophia Lane"}
												fonts={["BI;Open Runde/Medium/v0"]}
												layoutDependency={layoutDependency}
												layoutId={"IzRU7mwai"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={sJR8wjB1z}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														style={{
															"--font-selector":
																"Qkk7T3BlbiBSdW5kZS9NZWRpdW0vdjA=",
															"--framer-font-family":
																'"Open Runde", "Open Runde Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
															"--framer-font-weight": "500",
															"--framer-line-height": "150%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
														}}
													>
														{"Dyna Phils"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1b48dph"}
												data-framer-name={"Marketing Consultant"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"qs_aN0u5g"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={UmQTZ_sR3}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1lpqzqx"}
														data-styles-preset={"uwmmbeA4Q"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112)))",
														}}
													>
														{"Head of Marketing"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={34}
											{...addPropertyOverrides(
												{
													LZbvw34aB: {
														y:
															(componentViewport?.y || 0) +
															8 +
															28 +
															(0 +
																257 +
																((((componentViewport?.height || 480) - 16) *
																	1 -
																	56 -
																	482) /
																	1) *
																	1) +
															95.5,
													},
													q1SCU0o7w: {
														y:
															(componentViewport?.y || 0) +
															8 +
															223 +
															0 +
															297 +
															95.5,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-f1xp6b-container"}
												layoutDependency={layoutDependency}
												layoutId={"vpwZhx0JF-container"}
												nodeId={"vpwZhx0JF"}
												rendersWithMotion={true}
												scopeId={"ceNjEn0pZ"}
											>
												{_jsx(stdin_default, {
													suppressHydrationWarning: true,
													cRZkWhGy9: jnnkAQ3vy,
													height: "100%",
													id: "vpwZhx0JF",
													klJrZSsm3: UYzjJfLeu,
													layoutId: "vpwZhx0JF",
													variant: bYzbMW5xc,
													width: "100%",
													XQBi6J5Qe: p_ifO2pfK,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-170txb7"}
											data-framer-name={"Author Image"}
											layoutDependency={layoutDependency}
											layoutId={"jsho6LO3I"}
											style={{
												backgroundColor: "rgb(255, 255, 255)",
												borderBottomLeftRadius: 1e3,
												borderBottomRightRadius: 1e3,
												borderTopLeftRadius: 1e3,
												borderTopRightRadius: 1e3,
											}}
										>
											<Image
												suppressHydrationWarning={true}
												background={{
													alt: "",
													fit: "fill",
													pixelHeight: 1200,
													pixelWidth: 800,
													sizes: "60px",
													src: "https://framerusercontent.com/images/S9L8waMJbCRGmORsmjIGSc17h8k.png?width=800&height=1200",
													srcSet:
														"https://framerusercontent.com/images/S9L8waMJbCRGmORsmjIGSc17h8k.png?scale-down-to=1024&width=800&height=1200 682w,https://framerusercontent.com/images/S9L8waMJbCRGmORsmjIGSc17h8k.png?width=800&height=1200 800w",
												}}
												className={"framer-165s6y6"}
												data-border={true}
												data-framer-name={"Image"}
												layoutDependency={layoutDependency}
												layoutId={"QpX_HKoJG"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgb(255, 255, 255)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
													borderBottomLeftRadius: 100,
													borderBottomRightRadius: 100,
													borderTopLeftRadius: 100,
													borderTopRightRadius: 100,
												}}
												{...addPropertyOverrides(
													{
														LZbvw34aB: {
															background: {
																alt: "",
																fit: "fill",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		8 +
																		28 +
																		(0 +
																			257 +
																			((((componentViewport?.height || 480) -
																				16) *
																				1 -
																				56 -
																				482) /
																				1) *
																				1) +
																		80.5 +
																		2,
																),
																sizes: "48px",
																...toResponsiveImage(MJJvWwU0l),
															},
														},
														q1SCU0o7w: {
															background: {
																alt: "",
																fit: "fill",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		8 +
																		223 +
																		0 +
																		297 +
																		80.5 +
																		2,
																),
																sizes: "48px",
																...toResponsiveImage(MJJvWwU0l),
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</motion.div>
									</motion.div>
								)}
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8oVXz.framer-1y3hldv, .framer-8oVXz .framer-1y3hldv { display: block; }",
	".framer-8oVXz.framer-xi0zcq { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 462px; }",
	".framer-8oVXz .framer-u8cig0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oVXz .framer-c1s8jz { flex: 1 0 0px; height: 266px; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oVXz .framer-v571wp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-8oVXz .framer-rfsf8b { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-8oVXz .framer-7gkkne { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-8oVXz .framer-kpxp4c { --framer-text-wrap-override: balance; -webkit-user-select: none; flex: none; height: auto; pointer-events: auto; position: relative; user-select: none; width: 100%; }",
	".framer-8oVXz .framer-21sj8d { -webkit-user-select: none; flex: none; height: auto; pointer-events: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-8oVXz .framer-15h42sa-container, .framer-8oVXz .framer-f1xp6b-container { flex: none; height: auto; position: relative; width: auto; z-index: 1; }",
	".framer-8oVXz .framer-cxem4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-8oVXz .framer-1prulzd { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-8oVXz .framer-93ve88, .framer-8oVXz .framer-1b48dph { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-8oVXz .framer-170txb7 { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 64px); overflow: hidden; position: relative; width: 64px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oVXz .framer-165s6y6 { bottom: 2px; flex: none; left: 2px; position: absolute; right: 2px; top: 2px; }",
	".framer-8oVXz.framer-v-19d003x.framer-xi0zcq { flex-direction: row; gap: 32px; height: 480px; padding: 8px 32px 8px 8px; width: 1193px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oVXz.framer-v-19d003x .framer-u8cig0 { flex: 1 0 0px; height: 100%; width: 1px; }",
	".framer-8oVXz.framer-v-19d003x .framer-c1s8jz { height: 100%; }",
	".framer-8oVXz.framer-v-19d003x .framer-v571wp { flex: 1 0 0px; gap: unset; height: 100%; justify-content: space-between; padding: 28px 0px 28px 0px; width: 1px; }",
	".framer-8oVXz.framer-v-19d003x .framer-rfsf8b, .framer-8oVXz.framer-v-1aa92vq .framer-rfsf8b { align-content: flex-start; align-items: flex-start; flex-direction: column; }",
	".framer-8oVXz.framer-v-19d003x .framer-7gkkne, .framer-8oVXz.framer-v-1aa92vq .framer-7gkkne { flex: none; order: 1; width: 100%; }",
	".framer-8oVXz.framer-v-19d003x .framer-15h42sa-container, .framer-8oVXz.framer-v-1aa92vq .framer-15h42sa-container, .framer-8oVXz.framer-v-19d003x.hover .framer-c1s8jz { order: 0; }",
	".framer-8oVXz.framer-v-19d003x .framer-1prulzd, .framer-8oVXz.framer-v-1aa92vq .framer-1prulzd { order: 1; }",
	".framer-8oVXz.framer-v-19d003x .framer-f1xp6b-container, .framer-8oVXz.framer-v-1aa92vq .framer-f1xp6b-container { order: 2; }",
	".framer-8oVXz.framer-v-19d003x .framer-170txb7 { height: var(--framer-aspect-ratio-supported, 52px); order: 0; width: 52px; }",
	".framer-8oVXz.framer-v-1aa92vq.framer-xi0zcq { cursor: unset; gap: 24px; padding: 8px 8px 32px 8px; width: 350px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oVXz.framer-v-1aa92vq .framer-c1s8jz { height: 199px; }",
	".framer-8oVXz.framer-v-1aa92vq .framer-v571wp { gap: 40px; justify-content: flex-start; padding: 0px 16px 0px 16px; }",
	".framer-8oVXz.framer-v-1aa92vq .framer-170txb7 { order: 0; width: 52px; }",
	".framer-8oVXz.framer-v-19d003x.hover .framer-v571wp { gap: unset; }",
	...css4,
	...css2,
	...css3,
	...css,
	'.framer-8oVXz[data-border="true"]::after, .framer-8oVXz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerceNjEn0pZ = withCSS(Component, css5, "framer-8oVXz");
var stdin_default2 = FramerceNjEn0pZ;
FramerceNjEn0pZ.displayName = "Blog Card";
FramerceNjEn0pZ.defaultProps = {
	height: 314,
	width: 462,
};
addPropertyControls(FramerceNjEn0pZ, {
	variant: {
		options: ["s4FWatjEv", "LZbvw34aB", "q1SCU0o7w"],
		optionTitles: ["Small", "Wide - Desktop", "Wide - Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	GCByEC9Fx: {
		defaultValue: "Label",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	pLYLm0921: {
		defaultValue:
			"Use this to present your focused, personal support coaching, consulting, mentoring or therapy.",
		displayTextArea: true,
		title: "Summary",
		type: ControlType.String,
	},
	OY2qPhaGN: {
		title: "Main Image",
		type: ControlType.ResponsiveImage,
	},
	MJJvWwU0l: {
		title: "Author Image",
		type: ControlType.ResponsiveImage,
	},
	sJR8wjB1z: {
		defaultValue: "Dyna Phils",
		displayTextArea: false,
		title: "Author Name",
		type: ControlType.String,
	},
	UmQTZ_sR3: {
		defaultValue: "Head of Marketing",
		displayTextArea: false,
		title: "Author Position",
		type: ControlType.String,
	},
	bYzbMW5xc: BadgeControls?.["variant"] && {
		...BadgeControls["variant"],
		defaultValue: "Y6mBL48e4",
		description: void 0,
		hidden: void 0,
		title: "Badge Variant",
	},
	p_ifO2pfK: {
		defaultValue: "Tools",
		displayTextArea: false,
		title: "Badge/Category Name",
		type: ControlType.String,
	},
	UYzjJfLeu: {
		defaultValue:
			'var(--token-8ce91be8-4a20-4537-9973-9f2ad4c619f7, rgb(244, 241, 238)) /* {"name":"Beige 10"} */',
		title: "Badge Bg Color",
		type: ControlType.Color,
	},
	jnnkAQ3vy: {
		defaultValue:
			'var(--token-c508d2b6-c5a0-4393-9b17-65065c0b01a4, rgb(97, 74, 68)) /* {"name":"Dark Brown"} */',
		title: "Badge Text Color",
		type: ControlType.Color,
	},
	cCFzCovcz: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerceNjEn0pZ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Open Runde",
					source: "builtIn",
					style: "normal",
					url: "https://framerusercontent.com/assets/HJY4SY2JywrSZ2l1AEW9Tm9cO8.woff2",
					weight: "500",
				},
			],
		},
		...BadgeFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blog-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "q1SCU0o7w",
	xl: "LZbvw34aB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var blog_card_default = ComponentWithRoot;
export { blog_card_default as default };
