// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * appImage?: {src: string, srcSet?: string, alt?: string} // App Image
 * followers?: string // Followers
 * appName?: string // App Name
 * summary?: string // Summary
 * link?: string // Link
 * linkTitle?: string // Link Title
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KZKBIQL7.js";
import { className, css, fonts } from "./chunks/chunk-6CLJHUBU.js";
import { stdin_default } from "./chunks/chunk-KGAIBNJG.js";
import "./chunks/chunk-ESTNRGIO.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:community-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bHV8MsLPAjrsuFhrdp92/75xs3IgpenY1YL7d4L8u/qNOTomklG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/EgsDjgk7C2CaLUuC4LuC/V4HPVf2FrOaSsto8YMsQ/XPGja3vc1.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Runde/Semibold/v0"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
				weight: "600",
			},
		],
	},
];
var css3 = [
	`.framer-oPKh4 .framer-styles-preset-cbi2pr:not(.rich-text-wrapper), .framer-oPKh4 .framer-styles-preset-cbi2pr.rich-text-wrapper h5 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-oPKh4 .framer-styles-preset-cbi2pr:not(.rich-text-wrapper), .framer-oPKh4 .framer-styles-preset-cbi2pr.rich-text-wrapper h5 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-oPKh4 .framer-styles-preset-cbi2pr:not(.rich-text-wrapper), .framer-oPKh4 .framer-styles-preset-cbi2pr.rich-text-wrapper h5 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 140%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-oPKh4";

// /:https://framerusercontent.com/modules/bHV8MsLPAjrsuFhrdp92/75xs3IgpenY1YL7d4L8u/qNOTomklG.js
var MainButtonFonts = getFonts(stdin_default);
var cycleOrder = ["wGXcwV1xX", "tC_dzf5Xr"];
var serializationHash = "framer-qIJGz";
var variantClassNames = {
	tC_dzf5Xr: "framer-v-sw97zl",
	wGXcwV1xX: "framer-v-y36fui",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "wGXcwV1xX",
	Mobile: "tC_dzf5Xr",
};
var getProps = ({
	appImage,
	appName,
	followers,
	height,
	id,
	link,
	linkTitle,
	summary,
	width,
	...props
}) => {
	return {
		...props,
		C0cJCgT25: appName ?? props.C0cJCgT25 ?? "Discord",
		cvMU92hp0: followers ?? props.cvMU92hp0 ?? "32K members",
		DfoPGXjxr:
			summary ??
			props.DfoPGXjxr ??
			"Stay updated on new features and discover how others are using Freelio.",
		m9lesnSoM: link ?? props.m9lesnSoM,
		ORGRLq7X7: appImage ?? props.ORGRLq7X7,
		QWxn6UVQ_: linkTitle ?? props.QWxn6UVQ_ ?? "Join community",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "wGXcwV1xX",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ORGRLq7X7,
		cvMU92hp0,
		C0cJCgT25,
		DfoPGXjxr,
		m9lesnSoM,
		QWxn6UVQ_,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "wGXcwV1xX",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-y36fui",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"wGXcwV1xX"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(255, 255, 255, 0)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(10px)",
							backgroundColor: "rgba(255, 255, 255, 0.7)",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							WebkitBackdropFilter: "blur(10px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								tC_dzf5Xr: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-qsvmm8"}
							data-framer-name={"App Logo + Follow Text"}
							layoutDependency={layoutDependency}
							layoutId={"XJoeQt3Ou"}
						>
							<Image
								suppressHydrationWarning={true}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 32 + 0 + 0,
									),
									sizes: "64px",
									...toResponsiveImage(ORGRLq7X7),
								}}
								className={"framer-1hhl4n6"}
								data-framer-name={"App Logo"}
								layoutDependency={layoutDependency}
								layoutId={"Aaq6Q3S1O"}
								style={{
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							/>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-1skl9mp"}
								data-framer-name={"32K members"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"q3dXdWCTO"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={cvMU92hp0}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-1goc2j9"}
										data-styles-preset={"lpN9RaA0p"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112)))",
										}}
									>
										{"32K members"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-oohcf3"}
							data-framer-name={"Texts"}
							layoutDependency={layoutDependency}
							layoutId={"dZnVNgNG_"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-14uyve2"}
								data-framer-name={"Discord"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Ap742o9fG"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={C0cJCgT25}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h5
										suppressHydrationWarning={true}
										className={"framer-styles-preset-cbi2pr"}
										data-styles-preset={"XPGja3vc1"}
									>
										{"Discord"}
									</motion.h5>
								</React.Fragment>
							</RichText>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-4ytt5p"}
								data-framer-name={
									"Stay updated on new features and discover how others are using Freelio."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"IYzoWwmsR"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={DfoPGXjxr}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-rsfkj"}
										data-styles-preset={"q2ShOlRIr"}
									>
										{
											"Stay updated on new features and discover how others are using Freelio."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={55}
							y={(componentViewport?.y || 0) + 32 + 310.2}
							{...addPropertyOverrides(
								{
									tC_dzf5Xr: {
										width: `calc(${componentViewport?.width || "100vw"} - 64px)`,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1yp9xja-container"}
								layoutDependency={layoutDependency}
								layoutId={"GrppC5N4H-container"}
								nodeId={"GrppC5N4H"}
								rendersWithMotion={true}
								scopeId={"qNOTomklG"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									ektwzyaAy: QWxn6UVQ_,
									FHCLGB0I0:
										"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
									height: "100%",
									id: "GrppC5N4H",
									layoutId: "GrppC5N4H",
									qomMPfTNC: {
										borderColor: "rgb(227, 225, 225)",
										borderStyle: "solid",
										borderWidth: 1,
									},
									variant: "cMgcydVG6",
									width: "100%",
									yPsg9PA2x: m9lesnSoM,
									...addPropertyOverrides(
										{
											tC_dzf5Xr: {
												style: {
													width: "100%",
												},
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qIJGz.framer-1qbmqqx, .framer-qIJGz .framer-1qbmqqx { display: block; }",
	".framer-qIJGz.framer-y36fui { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 32px; position: relative; width: 464px; will-change: var(--framer-will-change-override, transform); }",
	".framer-qIJGz .framer-qsvmm8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-qIJGz .framer-1hhl4n6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 64px; justify-content: flex-start; overflow: hidden; padding: 15px; position: relative; width: 64px; will-change: var(--framer-will-change-override, transform); }",
	".framer-qIJGz .framer-1skl9mp { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-qIJGz .framer-oohcf3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-qIJGz .framer-14uyve2, .framer-qIJGz .framer-4ytt5p { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-qIJGz .framer-1yp9xja-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-qIJGz.framer-v-sw97zl .framer-1yp9xja-container { width: 100%; }",
	...css,
	...css3,
	...css2,
	'.framer-qIJGz[data-border="true"]::after, .framer-qIJGz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerqNOTomklG = withCSS(Component, css4, "framer-qIJGz");
var stdin_default2 = FramerqNOTomklG;
FramerqNOTomklG.displayName = "Community Card";
FramerqNOTomklG.defaultProps = {
	height: 348,
	width: 464,
};
addPropertyControls(FramerqNOTomklG, {
	variant: {
		options: ["wGXcwV1xX", "tC_dzf5Xr"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ORGRLq7X7: {
		title: "App Image",
		type: ControlType.ResponsiveImage,
	},
	cvMU92hp0: {
		defaultValue: "32K members",
		displayTextArea: false,
		title: "Followers",
		type: ControlType.String,
	},
	C0cJCgT25: {
		defaultValue: "Discord",
		displayTextArea: false,
		title: "App Name",
		type: ControlType.String,
	},
	DfoPGXjxr: {
		defaultValue:
			"Stay updated on new features and discover how others are using Freelio.",
		displayTextArea: false,
		title: "Summary",
		type: ControlType.String,
	},
	m9lesnSoM: {
		title: "Link",
		type: ControlType.Link,
	},
	QWxn6UVQ_: {
		defaultValue: "Join community",
		displayTextArea: false,
		title: "Link Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerqNOTomklG,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MainButtonFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:community-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tC_dzf5Xr",
	xl: "wGXcwV1xX",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CommunityCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var community_card_default = ComponentWithRoot;
export { community_card_default as default };
