// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
}} Props

 */
import {
	stdin_default,
	stdin_default2 as stdin_default3,
} from "./chunks/chunk-Q7AS5YL6.js";
import { className, css, fonts } from "./chunks/chunk-6CLJHUBU.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7XAY5VTW.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-SODYEVIK.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/k0TjP1fO1otXfx4SkNYm/NeXGIEnBtpSsfurd6STO/B9uyFXSMa.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/JNI0unvKLnSNOjYgWQPe/cFK4x7HnGbxoZXkZNw5W/hNcHJzSkR.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0.75 18 C 0.336 18 0 17.664 0 17.25 L 0 0.75 C 0 0.336 0.336 0 0.75 0 L 17.25 0 C 17.664 0 18 0.336 18 0.75 L 18 17.25 C 18 17.664 17.664 18 17.25 18 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="ubm8tT7Gs" transform="translate(3 3)" width="18px"/><path d="M 0.75 18 C 0.336 18 0 17.664 0 17.25 L 0 0.75 C 0 0.336 0.336 0 0.75 0 L 17.25 0 C 17.664 0 18 0.336 18 0.75 L 18 17.25 C 18 17.664 17.664 18 17.25 18 Z" fill="transparent" height="18px" id="uLIbokj1X" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 0 L 0 6" fill="transparent" height="6px" id="wcL4Xtw6S" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(11.25 10.5)" width="1px"/><path d="M 0 0 L 0 6" fill="transparent" height="6px" id="haFqKG9T6" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 10.5)" width="1px"/><path d="M 0 2.625 C 0 1.175 1.175 0 2.625 0 C 4.075 0 5.25 1.175 5.25 2.625 L 5.25 6" fill="transparent" height="6px" id="ldXP7NTX2" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(11.25 10.5)" width="5.25px"/><path d="M 0 1.125 C 0 0.504 0.504 0 1.125 0 C 1.746 0 2.25 0.504 2.25 1.125 C 2.25 1.746 1.746 2.25 1.125 2.25 C 0.504 2.25 0 1.746 0 1.125 Z" fill="var(--21h8s6, rgb(0, 0, 0))" height="2.25px" id="M86o3vn0T" transform="translate(7.125 6.75)" width="2.25px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("4033599021", svg);
	return (
		<SVG
			suppressHydrationWarning={true}
			{...restProps}
			className={cx("framer-qVh2c", className4)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG>
	);
});
var css3 = [
	`.framer-qVh2c { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-qVh2c");
Icon.displayName = "Linkedin Logo";
var stdin_default4 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/zhSCPrWFamMDbQldHOq0/gnnBnQvZmkHR2mPs4gc9/mENJ1lRQL.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css4 = [
	".framer-ZnuK4 .framer-styles-preset-1is8sz4:not(.rich-text-wrapper), .framer-ZnuK4 .framer-styles-preset-1is8sz4.rich-text-wrapper a { --framer-link-current-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-link-hover-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-link-hover-text-decoration: underline; --framer-link-hover-text-decoration-style: dotted; --framer-link-text-color: var(--token-b11f95a4-bdbc-426c-b836-3f8af50cb50f, #453f3d); transition-delay: 0s; transition-duration: 0.4s; transition-property: color; transition-timing-function: cubic-bezier(0.44, 0, 0.56, 1); }",
];
var className3 = "framer-ZnuK4";

// /:https://framerusercontent.com/modules/k0TjP1fO1otXfx4SkNYm/NeXGIEnBtpSsfurd6STO/B9uyFXSMa.js
var ComponentLogoFonts = getFonts(stdin_default2);
var SocialMediaButtonFonts = getFonts(stdin_default3);
var cycleOrder = ["kk41sA_RO", "eil5YvXR7"];
var serializationHash = "framer-xSM0j";
var variantClassNames = {
	eil5YvXR7: "framer-v-1yj5c67",
	kk41sA_RO: "framer-v-195qthm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Desktop: "kk41sA_RO",
	Mobile: "eil5YvXR7",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kk41sA_RO",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kk41sA_RO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion2.footer
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-195qthm",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"kk41sA_RO"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(117, 115, 114, 0.15)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(5px)",
							backgroundColor: "rgba(255, 255, 255, 0.25)",
							borderBottomLeftRadius: 32,
							borderBottomRightRadius: 32,
							borderTopLeftRadius: 32,
							borderTopRightRadius: 32,
							WebkitBackdropFilter: "blur(5px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								eil5YvXR7: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-zzf8ie"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"crn2ColOS"}
						>
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-1m6ax7s"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"lIcjeIke5"}
							>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-12zvoz8"}
									data-framer-name={"Left"}
									layoutDependency={layoutDependency}
									layoutId={"EfQdLrULS"}
								>
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-4y43s4"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"yApUvNdPd"}
									>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={24}
											y={
												(componentViewport?.y || 0) +
												40 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides(
												{
													eil5YvXR7: {
														y:
															(componentViewport?.y || 0) +
															24 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-g5sdse-container"}
												layoutDependency={layoutDependency}
												layoutId={"vJCxWZcNP-container"}
												nodeId={"vJCxWZcNP"}
												rendersWithMotion={true}
												scopeId={"B9uyFXSMa"}
											>
												{_jsx2(stdin_default2, {
													suppressHydrationWarning: true,
													height: "100%",
													id: "vJCxWZcNP",
													layoutId: "vJCxWZcNP",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-hr1wy8"}
											data-framer-name={
												"Your favourite business management software."
											}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"OatjXQ3Jg"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1f5jbyr"}
													data-styles-preset={"oM4DrnKwh"}
												>
													{
														"Your favourite business management software. Built for early startup founders."
													}
												</motion2.p>
											</React2.Fragment>
										</RichText>
									</motion2.div>
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-14sri7w"}
										data-framer-name={"Social Media Links"}
										layoutDependency={layoutDependency}
										layoutId={"D06qc8apr"}
									>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={40}
											width={"40px"}
											y={
												(componentViewport?.y || 0) +
												40 +
												0 +
												0 +
												0 +
												0 +
												0 +
												184 +
												0
											}
											{...addPropertyOverrides(
												{
													eil5YvXR7: {
														y:
															(componentViewport?.y || 0) +
															24 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															184 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-gn0qrf-container"}
												layoutDependency={layoutDependency}
												layoutId={"VQHygiDK2-container"}
												nodeId={"VQHygiDK2"}
												rendersWithMotion={true}
												scopeId={"B9uyFXSMa"}
											>
												{_jsx2(stdin_default3, {
													suppressHydrationWarning: true,
													height: "100%",
													id: "VQHygiDK2",
													layoutId: "VQHygiDK2",
													obEzJs3YA: stdin_default4,
													style: {
														height: "100%",
														width: "100%",
													},
													wGBcLqS6q:
														"https://www.linkedin.com/in/leon-chike-39b753324/",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={40}
											width={"40px"}
											y={
												(componentViewport?.y || 0) +
												40 +
												0 +
												0 +
												0 +
												0 +
												0 +
												184 +
												0
											}
											{...addPropertyOverrides(
												{
													eil5YvXR7: {
														y:
															(componentViewport?.y || 0) +
															24 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															184 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-gzduf-container"}
												layoutDependency={layoutDependency}
												layoutId={"OKw2YDS1e-container"}
												nodeId={"OKw2YDS1e"}
												rendersWithMotion={true}
												scopeId={"B9uyFXSMa"}
											>
												{_jsx2(stdin_default3, {
													suppressHydrationWarning: true,
													height: "100%",
													id: "OKw2YDS1e",
													layoutId: "OKw2YDS1e",
													obEzJs3YA: stdin_default,
													style: {
														height: "100%",
														width: "100%",
													},
													wGBcLqS6q: "https://x.com/LeonC7303",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion2.div>
								</motion2.div>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-rxvtor"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"bQAwBMBuc"}
								>
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-13jqja4"}
										data-framer-name={"Pages"}
										layoutDependency={layoutDependency}
										layoutId={"INbp0kldP"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-mwagkv"}
											data-framer-name={"Pages"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"HgRVJfppZ"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1goc2j9"}
													data-styles-preset={"lpN9RaA0p"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
													}}
												>
													{"Pages"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-19tdctk"}
											data-framer-name={"Menus"}
											layoutDependency={layoutDependency}
											layoutId={"kliaI7fSk"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-57jjw7"}
												data-framer-name={"Reddit"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"fTMx8kftG"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																webPageId: "obBLBu_h4",
															}}
															motionChild={true}
															nodeId={"fTMx8kftG"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Home"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-191ps4h"}
												data-framer-name={"YouTube"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"SQohVqw_1"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																hash: ":VMJGhIahi",
																webPageId: "obBLBu_h4",
															}}
															motionChild={true}
															nodeId={"SQohVqw_1"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Features"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1wzm3jd"}
												data-framer-name={"X/Twitter"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"qvhz6tSLk"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																hash: ":g7Iswtddg",
																webPageId: "obBLBu_h4",
															}}
															motionChild={true}
															nodeId={"qvhz6tSLk"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Pricing"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-5l4dhe"}
												data-framer-name={"Slack"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"WfQ2aHAdz"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																webPageId: "otG8ouHU2",
															}}
															motionChild={true}
															nodeId={"WfQ2aHAdz"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Blog"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
									</motion2.div>
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-rqkxc8"}
										data-framer-name={"Information"}
										layoutDependency={layoutDependency}
										layoutId={"snn_ygYrr"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1gzumvs"}
											data-framer-name={"community"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Ei8vX7NDJ"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1goc2j9"}
													data-styles-preset={"lpN9RaA0p"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
													}}
												>
													{"information"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-1w0jcwy"}
											data-framer-name={"Menus"}
											layoutDependency={layoutDependency}
											layoutId={"eXmwayTuM"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-19czcau"}
												data-framer-name={"Reddit"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"JCCDbWa7u"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																webPageId: "XzDpWUuVS",
															}}
															motionChild={true}
															nodeId={"JCCDbWa7u"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Contact"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1aprczf"}
												data-framer-name={"YouTube"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"l0AFXJOb_"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																webPageId: "XnXPxwXFP",
															}}
															motionChild={true}
															nodeId={"l0AFXJOb_"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Privacy"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1p3l32t"}
												data-framer-name={"Slack"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"BwvUUXDr8"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																webPageId: "hsgBIwJa9",
															}}
															motionChild={true}
															nodeId={"BwvUUXDr8"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"Terms of use"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-ka9oa3"}
												data-framer-name={"Slack"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Nc2_PLUtF"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1f5jbyr"}
														data-styles-preset={"oM4DrnKwh"}
													>
														<Link
															suppressHydrationWarning={true}
															href={{
																webPageId: "Wk3v0LVLV",
															}}
															motionChild={true}
															nodeId={"Nc2_PLUtF"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"B9uyFXSMa"}
															smoothScroll={false}
														>
															<motion2.a
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1is8sz4"}
																data-styles-preset={"mENJ1lRQL"}
															>
																{"404"}
															</motion2.a>
														</Link>
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
									</motion2.div>
								</motion2.div>
							</motion2.div>
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-g4yge5"}
								data-border={true}
								data-framer-name={"Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"g5mTrwe2Q"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(117, 113, 112, 0.2)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								}}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-f44d6s"}
									data-framer-name={
										"Your favourite business management software."
									}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"oNtPjQoW_"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											eil5YvXR7: {
												children: (
													<React2.Fragment>
														<motion2.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-1f5jbyr"}
															data-styles-preset={"oM4DrnKwh"}
															style={{
																"--framer-text-alignment": "center",
															}}
														>
															{"\xA9 2025 Dreelio. Created by "}
															<Link
																suppressHydrationWarning={true}
																href={"https://leonchike.com"}
																motionChild={true}
																nodeId={"oNtPjQoW_"}
																openInNewTab={true}
																relValues={[]}
																scopeId={"B9uyFXSMa"}
																smoothScroll={false}
															>
																<motion2.a
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-1is8sz4"}
																	data-styles-preset={"mENJ1lRQL"}
																>
																	<motion2.strong
																		suppressHydrationWarning={true}
																	>
																		{"Leon Chike"}
																	</motion2.strong>
																</motion2.a>
															</Link>
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1f5jbyr"}
											data-styles-preset={"oM4DrnKwh"}
										>
											{"\xA9 2025 Dreelio. Created by "}
											<Link
												suppressHydrationWarning={true}
												href={"https://leonchike.com"}
												motionChild={true}
												nodeId={"oNtPjQoW_"}
												openInNewTab={true}
												relValues={[]}
												scopeId={"B9uyFXSMa"}
												smoothScroll={false}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1is8sz4"}
													data-styles-preset={"mENJ1lRQL"}
												>
													<motion2.strong suppressHydrationWarning={true}>
														{"Leon Chike"}
													</motion2.strong>
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-9o25ol"}
									data-framer-name={
										"Your favourite business management software."
									}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"YkGRYxilJ"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1f5jbyr"}
											data-styles-preset={"oM4DrnKwh"}
										>
											<Link
												suppressHydrationWarning={true}
												href={"https://framer.link/leonardo-chike"}
												motionChild={true}
												nodeId={"YkGRYxilJ"}
												openInNewTab={true}
												relValues={[]}
												scopeId={"B9uyFXSMa"}
												smoothScroll={false}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1is8sz4"}
													data-styles-preset={"mENJ1lRQL"}
												>
													{"Built in "}
													<motion2.strong suppressHydrationWarning={true}>
														{"Framer"}
													</motion2.strong>
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						</motion2.div>
					</motion2.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xSM0j.framer-1hnrgpy, .framer-xSM0j .framer-1hnrgpy { display: block; }",
	".framer-xSM0j.framer-195qthm { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px; position: relative; width: 1072px; }",
	".framer-xSM0j .framer-zzf8ie { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1072px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xSM0j .framer-1m6ax7s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xSM0j .framer-12zvoz8 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; max-width: 240px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-xSM0j .framer-4y43s4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xSM0j .framer-g5sdse-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-xSM0j .framer-hr1wy8, .framer-xSM0j .framer-mwagkv, .framer-xSM0j .framer-57jjw7, .framer-xSM0j .framer-191ps4h, .framer-xSM0j .framer-1wzm3jd, .framer-xSM0j .framer-5l4dhe, .framer-xSM0j .framer-1gzumvs, .framer-xSM0j .framer-19czcau, .framer-xSM0j .framer-1aprczf, .framer-xSM0j .framer-1p3l32t, .framer-xSM0j .framer-ka9oa3 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-xSM0j .framer-14sri7w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xSM0j .framer-gn0qrf-container, .framer-xSM0j .framer-gzduf-container { flex: none; height: 40px; position: relative; width: 40px; }",
	".framer-xSM0j .framer-rxvtor { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; max-width: 300px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-xSM0j .framer-13jqja4, .framer-xSM0j .framer-rqkxc8 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-xSM0j .framer-19tdctk, .framer-xSM0j .framer-1w0jcwy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xSM0j .framer-g4yge5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 32px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-xSM0j .framer-f44d6s { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-xSM0j .framer-9o25ol { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-xSM0j.framer-v-1yj5c67.framer-195qthm { padding: 24px; width: 350px; }",
	".framer-xSM0j.framer-v-1yj5c67 .framer-zzf8ie { gap: 48px; }",
	".framer-xSM0j.framer-v-1yj5c67 .framer-1m6ax7s { flex-direction: column; gap: 48px; justify-content: flex-start; }",
	".framer-xSM0j.framer-v-1yj5c67 .framer-12zvoz8 { flex: none; max-width: unset; width: 100%; }",
	".framer-xSM0j.framer-v-1yj5c67 .framer-rxvtor { flex: none; flex-direction: column; gap: 40px; max-width: unset; width: 100%; }",
	".framer-xSM0j.framer-v-1yj5c67 .framer-13jqja4, .framer-xSM0j.framer-v-1yj5c67 .framer-rqkxc8, .framer-xSM0j.framer-v-1yj5c67 .framer-f44d6s { flex: none; width: 100%; }",
	".framer-xSM0j.framer-v-1yj5c67 .framer-g4yge5 { flex-direction: column; gap: 12px; justify-content: center; padding: 24px 0px 0px 0px; }",
	...css2,
	...css,
	...css4,
	'.framer-xSM0j[data-border="true"]::after, .framer-xSM0j [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerB9uyFXSMa = withCSS2(Component2, css5, "framer-xSM0j");
var stdin_default5 = FramerB9uyFXSMa;
FramerB9uyFXSMa.displayName = "Footer";
FramerB9uyFXSMa.defaultProps = {
	height: 395,
	width: 1072,
};
addPropertyControls2(FramerB9uyFXSMa, {
	variant: {
		options: ["kk41sA_RO", "eil5YvXR7"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerB9uyFXSMa,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...ComponentLogoFonts,
		...SocialMediaButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var footer_default = ComponentWithRoot;
export { footer_default as default };
