// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ESTNRGIO.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:form-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/GrxzSlwbViirVNahu6g6/1pn6aZNJmtmSjSHmNbZa/AAFNBsmqF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	EaxXuBytE: {
		hover: true,
	},
};
var cycleOrder = [
	"EaxXuBytE",
	"sDY835aZ6",
	"Z8Gt1q9fS",
	"MHzOLAWmZ",
	"gyPa3nCSm",
];
var serializationHash = "framer-UGK2l";
var variantClassNames = {
	EaxXuBytE: "framer-v-475m3d",
	gyPa3nCSm: "framer-v-15z5sho",
	MHzOLAWmZ: "framer-v-63ayl",
	sDY835aZ6: "framer-v-1022wgy",
	Z8Gt1q9fS: "framer-v-u4mmlv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "EaxXuBytE",
	Disabled: "Z8Gt1q9fS",
	Error: "gyPa3nCSm",
	Loading: "sDY835aZ6",
	Success: "MHzOLAWmZ",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "EaxXuBytE",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "EaxXuBytE",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "sDY835aZ6") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "sDY835aZ6") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.button
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-475m3d",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"EaxXuBytE"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							opacity: 1,
							...style,
						}}
						variants={{
							"EaxXuBytE-hover": {
								backgroundColor: "rgba(26, 22, 21, 0.8)",
								opacity: 1,
							},
							gyPa3nCSm: {
								backgroundColor: "rgba(255, 34, 68, 0.15)",
								opacity: 1,
							},
							MHzOLAWmZ: {
								opacity: 1,
							},
							Z8Gt1q9fS: {
								opacity: 0.5,
							},
						}}
						{...addPropertyOverrides(
							{
								"EaxXuBytE-hover": {
									"data-framer-name": void 0,
								},
								gyPa3nCSm: {
									"data-framer-name": "Error",
								},
								MHzOLAWmZ: {
									"data-framer-name": "Success",
								},
								sDY835aZ6: {
									"data-framer-name": "Loading",
								},
								Z8Gt1q9fS: {
									"data-framer-name": "Disabled",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-roc820"}
								data-framer-name={"Texts Container"}
								layoutDependency={layoutDependency}
								layoutId={"LQPzGeRDp"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1d0ovbu"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"QEgMLTwP7"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									variants={{
										gyPa3nCSm: {
											"--extracted-r6o4lv": "rgb(247, 25, 58)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											gyPa3nCSm: {
												children: (
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-5iht5j"}
															data-styles-preset={"PNdcLES0J"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(247, 25, 58))",
															}}
														>
															{"Something went wrong"}
														</motion.p>
													</React.Fragment>
												),
											},
											MHzOLAWmZ: {
												children: (
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-5iht5j"}
															data-styles-preset={"PNdcLES0J"}
														>
															{"Thank you"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-5iht5j"}
											data-styles-preset={"PNdcLES0J"}
										>
											{"Send a message"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1tb6v7y"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"uffzIOaym"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									variants={{
										gyPa3nCSm: {
											"--extracted-r6o4lv": "rgb(247, 25, 58)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											gyPa3nCSm: {
												children: (
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-5iht5j"}
															data-styles-preset={"PNdcLES0J"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(247, 25, 58))",
															}}
														>
															{"Something went wrong"}
														</motion.p>
													</React.Fragment>
												),
											},
											MHzOLAWmZ: {
												children: (
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															className={"framer-styles-preset-5iht5j"}
															data-styles-preset={"PNdcLES0J"}
														>
															{"Thank you"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-5iht5j"}
											data-styles-preset={"PNdcLES0J"}
										>
											{"Send a message"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
						{isDisplayed1() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-l82lj5"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"NfaNXK7Jd"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									suppressHydrationWarning={true}
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-rp0oix"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"GnrOzpRYs"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										sDY835aZ6: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1l75tu8"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"R8e4bnnV5"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UGK2l.framer-15efxk7, .framer-UGK2l .framer-15efxk7 { display: block; }",
	".framer-UGK2l.framer-475m3d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 55px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 240px; }",
	".framer-UGK2l .framer-roc820 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 20px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-UGK2l .framer-1d0ovbu, .framer-UGK2l .framer-1tb6v7y { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-UGK2l .framer-l82lj5 { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-UGK2l .framer-rp0oix { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-UGK2l .framer-1l75tu8 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-UGK2l.framer-v-1022wgy.framer-475m3d, .framer-UGK2l.framer-v-u4mmlv.framer-475m3d, .framer-UGK2l.framer-v-63ayl.framer-475m3d, .framer-UGK2l.framer-v-15z5sho.framer-475m3d { cursor: unset; }",
	".framer-UGK2l.framer-v-1022wgy .framer-rp0oix { overflow: hidden; }",
	".framer-UGK2l.framer-v-475m3d.hover .framer-roc820 { justify-content: flex-end; }",
	...css,
];
var FramerAAFNBsmqF = withCSS(Component, css2, "framer-UGK2l");
var stdin_default = FramerAAFNBsmqF;
FramerAAFNBsmqF.displayName = "Form Button";
FramerAAFNBsmqF.defaultProps = {
	height: 55,
	width: 240,
};
addPropertyControls(FramerAAFNBsmqF, {
	variant: {
		options: ["EaxXuBytE", "sDY835aZ6", "Z8Gt1q9fS", "MHzOLAWmZ", "gyPa3nCSm"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerAAFNBsmqF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:form-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FormButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var form_button_default = ComponentWithRoot;
export { form_button_default as default };
