// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * tickerVariant?: 'Scroll' | 'Moving' // Ticker Variant
 * direction?: 'Left' | 'Right' | 'Top' | 'Bottom' // Direction
 * gap?: number // Gap
 * showImage01?: boolean // Show Image 01
 * image01?: {src: string, srcSet?: string, alt?: string} // Image 01
 * showImage02?: boolean // Show Image 02
 * image02?: {src: string, srcSet?: string, alt?: string} // Image 02
 * showImage03?: boolean // Show Image 03
 * image03?: {src: string, srcSet?: string, alt?: string} // Image 03
 * showImage04?: boolean // Show Image 04
 * image04?: {src: string, srcSet?: string, alt?: string} // Image 04
 * showImage05?: boolean // Show Image 05
 * image05?: {src: string, srcSet?: string, alt?: string} // Image 05
 * showImage06?: boolean // Show Image 06
 * image06?: {src: string, srcSet?: string, alt?: string} // Image 06
 * showImage07?: boolean // Show Image 07
 * image07?: {src: string, srcSet?: string, alt?: string} // Image 07
 * showImage08?: boolean // Show Image 08
 * image08?: {src: string, srcSet?: string, alt?: string} // Image 08
 * showImage09?: boolean // Show Image 09
 * image09?: {src: string, srcSet?: string, alt?: string} // Image 09
}} Props

 */
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:integrations-ticker
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/AOCoPI9dy5s7xokwzzqc/bq6Fpgez76WmcHPBA8vf/VE7jZqmTQ.js
import { jsx as _jsx4 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	getPropertyControls,
	Image,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/WVXJ5gQDkQ5V8fm9KUVE/y8KgG1vt8zaeurXgrJqu/TickerScroll_Prod.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	Children,
	useEffect,
	useState,
	useRef as useRef2,
	useMemo as useMemo2,
	createRef,
	useCallback,
	cloneElement as cloneElement2,
} from "react";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	RenderTarget,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	useMotionValue,
	useTransform,
	motion as motion2,
	frame,
} from "unframer";
import { resize } from "@motionone/dom";

// /:https://framerusercontent.com/modules/aej5zpwxBpkMdzOteBwy/DWeAZ5wauvGM5oFwVdgS/Utils.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import { cloneElement } from "react";

// /:https://framerusercontent.com/modules/fMDE7Cqb2uOvQFAHEP2m/cRfVFRl0izzBulKFjOAe/W7oLCU4_B.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-q8Ttd";
var variantClassNames = {
	XvqTw0Be9: "framer-v-jjcw9a",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var getProps = ({ height, id, subtitle, title, width, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		WuF2iG84P:
			(_ref =
				subtitle !== null && subtitle !== void 0
					? subtitle
					: props.WuF2iG84P) !== null && _ref !== void 0
				? _ref
				: "Set up the component by adding background and bouncer elements to the component properties.",
		yeAnKbEUZ:
			(_ref1 = title !== null && title !== void 0 ? title : props.yeAnKbEUZ) !==
				null && _ref1 !== void 0
				? _ref1
				: "Screen Saver",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		yeAnKbEUZ,
		WuF2iG84P,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "XvqTw0Be9",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-jjcw9a",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"XvqTw0Be9"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: "rgba(136, 85, 255, 0.1)",
							...style,
						}}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-uh2i08"}
							layoutDependency={layoutDependency}
							layoutId={"aM7oiNoFL"}
						>
							<SVG
								suppressHydrationWarning={true}
								className={"framer-flw0dh"}
								data-framer-name={"Logo"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"GthLmGmBt"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 28 28"><g id="ss11036020200_1"><path d="M 0 0 L 28 0 L 28 28 L 0 28 Z" fill="transparent"></path><path d="M 21 7.113 C 21 7.041 21.029 6.971 21.079 6.921 L 27.534 0.465 C 27.613 0.388 27.73 0.365 27.831 0.407 C 27.933 0.449 28 0.548 28 0.658 L 28 13.888 C 28 13.96 27.971 14.028 27.921 14.079 L 21 21 Z M 7 21 L 7 7.658 C 7 7.548 6.933 7.449 6.831 7.407 C 6.73 7.365 6.613 7.388 6.534 7.465 L 0.079 13.921 C 0.028 13.972 0 14.041 0 14.113 L 0 27.728 C 0 27.877 0.122 28 0.273 28 L 13.888 28 C 13.96 28 14.028 27.971 14.079 27.921 L 21 21 Z" fill="rgb(153, 102, 255)"></path></g></svg>'
								}
								svgContentId={11036020200}
								withExternalLayout={true}
							/>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-k3ullq"}
								layoutDependency={layoutDependency}
								layoutId={"E3DQBYSAf"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-q0gs4u"}
									data-framer-name={"Title"}
									fonts={["Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"UqJwZqJjg"}
									style={{
										"--extracted-r6o4lv": "rgb(153, 102, 255)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={yeAnKbEUZ}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector": "SW50ZXItQm9sZA==",
												"--framer-font-family":
													'"Inter", "Inter Placeholder", sans-serif',
												"--framer-font-size": "11px",
												"--framer-font-weight": "700",
												"--framer-letter-spacing": "-0.02em",
												"--framer-line-height": "1em",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(153, 102, 255))",
											}}
										>
											{"Screen Saver"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-g5dqhc"}
									data-framer-name={"Subtitle"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"RJ7UF99m8"}
									style={{
										"--extracted-r6o4lv": "rgba(153, 102, 255, 0.7)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={WuF2iG84P}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--framer-font-size": "11px",
												"--framer-letter-spacing": "-0.03em",
												"--framer-line-height": "1.4em",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgba(153, 102, 255, 0.7))",
											}}
										>
											{
												"Set up the component by adding background and bouncer elements to the component properties."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-q8Ttd.framer-qanqo2, .framer-q8Ttd .framer-qanqo2 { display: block; }",
	".framer-q8Ttd.framer-jjcw9a { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 200px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 400px; }",
	".framer-q8Ttd .framer-uh2i08 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 20px 0px 20px; position: relative; width: 1px; }",
	".framer-q8Ttd .framer-flw0dh { flex: none; height: 28px; position: relative; width: 28px; }",
	".framer-q8Ttd .framer-k3ullq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; max-width: 200px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-q8Ttd .framer-q0gs4u, .framer-q8Ttd .framer-g5dqhc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-q8Ttd.framer-jjcw9a, .framer-q8Ttd .framer-uh2i08, .framer-q8Ttd .framer-k3ullq { gap: 0px; } .framer-q8Ttd.framer-jjcw9a > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-q8Ttd.framer-jjcw9a > :first-child { margin-left: 0px; } .framer-q8Ttd.framer-jjcw9a > :last-child { margin-right: 0px; } .framer-q8Ttd .framer-uh2i08 > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-q8Ttd .framer-uh2i08 > :first-child, .framer-q8Ttd .framer-k3ullq > :first-child { margin-top: 0px; } .framer-q8Ttd .framer-uh2i08 > :last-child, .framer-q8Ttd .framer-k3ullq > :last-child { margin-bottom: 0px; } .framer-q8Ttd .framer-k3ullq > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
];
var FramerW7oLCU4_B = withCSS(Component, css, "framer-q8Ttd");
var stdin_default = FramerW7oLCU4_B;
FramerW7oLCU4_B.displayName = "Utils/Component Message";
FramerW7oLCU4_B.defaultProps = {
	height: 200,
	width: 400,
};
addPropertyControls(FramerW7oLCU4_B, {
	yeAnKbEUZ: {
		defaultValue: "Screen Saver",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	WuF2iG84P: {
		defaultValue:
			"Set up the component by adding background and bouncer elements to the component properties.",
		displayTextArea: false,
		title: "Subtitle",
		type: ControlType.String,
	},
});
addFonts(
	FramerW7oLCU4_B,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/aej5zpwxBpkMdzOteBwy/DWeAZ5wauvGM5oFwVdgS/Utils.js
var ComponentMessage = ({ title, subtitle, style }) => {
	return _jsx2(stdin_default, {
		suppressHydrationWarning: true,
		yeAnKbEUZ: title,
		WuF2iG84P: subtitle,
		style: {
			width: "100%",
			height: "100%",
			...style,
		},
	});
};

// /:https://framerusercontent.com/modules/WVXJ5gQDkQ5V8fm9KUVE/y8KgG1vt8zaeurXgrJqu/TickerScroll_Prod.js
import { isDesktop } from "react-device-detect";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var MAX_DUPLICATED_ITEMS = 100;
var directionTransformers = {
	left: (offset) => `translateX(-${offset}px)`,
	right: (offset) => `translateX(-${offset}px)`,
	top: (offset) => `translateY(-${offset}px)`,
	bottom: (offset) => `translateY(-${offset}px)`,
};
function VirtualScrollTicker(props) {
	const {
		slots,
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		speed,
		direction,
		alignment,
		sizingOptions,
		fadeOptions,
		style,
	} = props;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const { widthType, heightType } = sizingOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const filteredSlots = slots.filter(Boolean);
	const numChildren = Children.count(filteredSlots);
	const hasChildren = numChildren > 0;
	const isHorizontal = direction === "left" || direction === "right";
	const parentRef = useRef2(null);
	const childrenRef = useMemo2(() => {
		return [/* @__PURE__ */ createRef(), /* @__PURE__ */ createRef()];
	}, []);
	const [size, setSize] = useState({
		parent: null,
		children: null,
	});
	let clonedChildren = [];
	let dupedChildren = [];
	let duplicateBy = 0;
	let opacity = 0;
	if (isCanvas) {
		duplicateBy = numChildren ? Math.floor(10 / numChildren) : 0;
		opacity = 1;
	}
	if (!isCanvas && hasChildren && size.parent) {
		duplicateBy = Math.round((size.parent / size.children) * 2) + 1;
		duplicateBy = Math.min(duplicateBy, MAX_DUPLICATED_ITEMS);
		opacity = 1;
	}
	const measure = useCallback(() => {
		if (hasChildren && parentRef.current) {
			const parentLength = isHorizontal
				? parentRef.current.offsetWidth
				: parentRef.current.offsetHeight;
			const start = childrenRef[0].current
				? isHorizontal
					? childrenRef[0].current.offsetLeft
					: childrenRef[0].current.offsetTop
				: 0;
			const end = childrenRef[1].current
				? isHorizontal
					? childrenRef[1].current.offsetLeft +
						childrenRef[1].current.offsetWidth
					: childrenRef[1].current.offsetTop +
						childrenRef[1].current.offsetHeight
				: 0;
			const childrenLength = end - start + gap;
			setSize({
				parent: parentLength,
				children: childrenLength,
			});
		}
	}, []);
	const childrenStyles = isCanvas
		? {
				contentVisibility: "auto",
			}
		: {};
	if (hasChildren) {
		if (!isCanvas) {
			let initialResize = useRef2(true);
			useEffect(() => {
				frame.read(measure);
				return resize(parentRef.current, ({ contentSize }) => {
					if (
						!initialResize.current &&
						(contentSize.width || contentSize.height)
					) {
						frame.read(measure);
					}
					initialResize.current = false;
				});
			}, []);
		}
		clonedChildren = Children.map(filteredSlots, (child, index) => {
			var _child_props, _child_props1, _child_props2, _child_props3;
			let ref;
			if (index === 0) {
				ref = childrenRef[0];
			}
			if (index === filteredSlots.length - 1) {
				ref = childrenRef[1];
			}
			const size2 = {
				width: widthType
					? (_child_props = child.props) === null || _child_props === void 0
						? void 0
						: _child_props.width
					: "100%",
				height: heightType
					? (_child_props1 = child.props) === null || _child_props1 === void 0
						? void 0
						: _child_props1.height
					: "100%",
			};
			return (
				<LayoutGroup2 suppressHydrationWarning={true} inherit={"id"}>
					<li suppressHydrationWarning={true} ref={ref} style={size2}>
						{
							/* @__PURE__ */ cloneElement2(
								child,
								{
									style: {
										...((_child_props2 = child.props) === null ||
										_child_props2 === void 0
											? void 0
											: _child_props2.style),
										...size2,
										flexShrink: 0,
										...childrenStyles,
									},
									layoutId: child.props.layoutId
										? child.props.layoutId + "-original-" + index
										: void 0,
								},
								(_child_props3 = child.props) === null ||
									_child_props3 === void 0
									? void 0
									: _child_props3.children,
							)
						}
					</li>
				</LayoutGroup2>
			);
		});
	}
	if (!isCanvas) {
		for (let i = 0; i < duplicateBy; i++) {
			dupedChildren = [
				...dupedChildren,
				...Children.map(filteredSlots, (child, childIndex) => {
					var _child_props,
						_child_props1,
						_child_props2,
						_child_props3,
						_child_props4,
						_child_props5;
					const size2 = {
						width: widthType
							? (_child_props = child.props) === null || _child_props === void 0
								? void 0
								: _child_props.width
							: "100%",
						height: heightType
							? (_child_props1 = child.props) === null ||
								_child_props1 === void 0
								? void 0
								: _child_props1.height
							: "100%",
						willChange: "transform",
					};
					return (
						<LayoutGroup2 suppressHydrationWarning={true} inherit={"id"}>
							<li
								suppressHydrationWarning={true}
								style={size2}
								aria-hidden={true}
							>
								{
									/* @__PURE__ */ cloneElement2(
										child,
										{
											key: i + " " + childIndex,
											style: {
												...((_child_props2 = child.props) === null ||
												_child_props2 === void 0
													? void 0
													: _child_props2.style),
												width: widthType
													? (_child_props3 = child.props) === null ||
														_child_props3 === void 0
														? void 0
														: _child_props3.width
													: "100%",
												height: heightType
													? (_child_props4 = child.props) === null ||
														_child_props4 === void 0
														? void 0
														: _child_props4.height
													: "100%",
												flexShrink: 0,
												...childrenStyles,
											},
											layoutId: child.props.layoutId
												? child.props.layoutId + "-dupe-" + i
												: void 0,
										},
										(_child_props5 = child.props) === null ||
											_child_props5 === void 0
											? void 0
											: _child_props5.children,
									)
								}
							</li>
						</LayoutGroup2>
					);
				}),
			];
		}
	}
	const offset = useMotionValue(0);
	const transformer = directionTransformers[direction];
	const transform = useTransform(offset, transformer);
	useEffect(() => {
		if (!isCanvas && size.children) {
			let lastScrollY = __unframerWindow.scrollY;
			let targetOffset = 0;
			let currentOffset = 0;
			let animationFrameId = null;
			let animationOnTouchId = null;
			const updateOffset = () => {
				const scrollDiff = isDesktop
					? __unframerWindow.scrollY - lastScrollY
					: 0;
				lastScrollY = __unframerWindow.scrollY;
				switch (direction) {
					case "left":
					case "top":
						targetOffset += scrollDiff * speed;
						break;
					case "right":
					case "bottom":
						targetOffset -= scrollDiff * speed;
						break;
				}
				currentOffset += (targetOffset - currentOffset) * 0.1;
				if (currentOffset < 0) {
					currentOffset += size.children;
					targetOffset += size.children;
				} else if (currentOffset >= size.children) {
					currentOffset -= size.children;
					targetOffset -= size.children;
				}
				offset.set(currentOffset);
				animationFrameId = requestAnimationFrame(updateOffset);
			};
			animationFrameId = requestAnimationFrame(updateOffset);
			const handleWheel = (e) => {
				if (
					document.documentElement.scrollHeight <= __unframerWindow.innerHeight
				) {
					e.preventDefault();
					switch (direction) {
						case "left":
						case "top":
							targetOffset += e.deltaY * speed;
							break;
						case "right":
						case "bottom":
							targetOffset -= e.deltaY * speed;
							break;
					}
				}
			};
			const handleTouchDevice = () => {
				switch (direction) {
					case "left":
					case "top":
						targetOffset += speed;
						break;
					case "right":
					case "bottom":
						targetOffset -= speed;
						break;
				}
				animationOnTouchId = !isDesktop
					? requestAnimationFrame(handleTouchDevice)
					: null;
			};
			animationOnTouchId = requestAnimationFrame(handleTouchDevice);
			__unframerWindow.addEventListener("wheel", handleWheel, {
				passive: false,
			});
			return () => {
				__unframerWindow.removeEventListener("wheel", handleWheel);
				if (animationOnTouchId !== null) {
					cancelAnimationFrame(animationOnTouchId);
				}
				if (animationFrameId !== null) {
					cancelAnimationFrame(animationFrameId);
				}
			};
		}
	}, [speed, direction, size.children]);
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	if (!hasChildren) {
		return (
			<ComponentMessage
				suppressHydrationWarning={true}
				title={"Ticker Scroll Component"}
				subtitle={"Add layers or components to infinitely loop on your page."}
			/>
		);
	}
	return (
		<section
			suppressHydrationWarning={true}
			style={{
				...containerStyle,
				opacity,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				MozMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				overflow: overflow ? "visible" : "hidden",
				padding: paddingValue,
			}}
			ref={parentRef}
		>
			<motion2.ul
				suppressHydrationWarning={true}
				style={{
					...containerStyle,
					gap,
					placeItems: alignment,
					position: "relative",
					flexDirection: isHorizontal ? "row" : "column",
					...style,
					willChange: isCanvas ? "auto" : "transform",
					transform,
				}}
			>
				{clonedChildren}
				{dupedChildren}
			</motion2.ul>
		</section>
	);
}
VirtualScrollTicker.defaultProps = {
	gap: 10,
	padding: 10,
	speed: 0.5,
	sizingOptions: {
		widthType: true,
		heightType: true,
	},
	fadeOptions: {
		fadeContent: true,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	direction: "left",
};
VirtualScrollTicker.displayName = "Ticker Scroll";
addPropertyControls2(VirtualScrollTicker, {
	slots: {
		type: ControlType2.Array,
		title: "Children",
		control: {
			type: ControlType2.ComponentInstance,
		},
	},
	speed: {
		type: ControlType2.Number,
		title: "Speed",
		min: 0,
		max: 5,
		defaultValue: 0.5,
		step: 0.1,
		displayStepper: true,
	},
	direction: {
		type: ControlType2.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		defaultValue: "left",
		displaySegmentedControl: true,
	},
	alignment: {
		type: ControlType2.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	gap: {
		type: ControlType2.Number,
		title: "Gap",
	},
	padding: {
		title: "Padding",
		type: ControlType2.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	sizingOptions: {
		type: ControlType2.Object,
		title: "Sizing",
		controls: {
			widthType: {
				type: ControlType2.Boolean,
				title: "Width",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
			heightType: {
				type: ControlType2.Boolean,
				title: "Height",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
		},
	},
	fadeOptions: {
		type: ControlType2.Object,
		title: "Clipping",
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
		controls: {
			fadeContent: {
				type: ControlType2.Boolean,
				title: "Fade",
				defaultValue: true,
			},
			overflow: {
				type: ControlType2.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType2.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType2.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType2.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
});
var containerStyle = {
	display: "flex",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);

// /:https://framerusercontent.com/modules/AOCoPI9dy5s7xokwzzqc/bq6Fpgez76WmcHPBA8vf/VE7jZqmTQ.js
var TickerScrollFonts = getFonts(VirtualScrollTicker);
var TickerScrollControls = getPropertyControls(VirtualScrollTicker);
var serializationHash2 = "framer-Xxntd";
var variantClassNames2 = {
	KrdgdKYgh: "framer-v-visix6",
};
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var equals = (a, b) => {
	return typeof a === "string" && typeof b === "string"
		? a.toLowerCase() === b.toLowerCase()
		: a === b;
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion3.create(React2.Fragment);
var humanReadableEnumMap = {
	Moving: "fhgdpkffP",
	Scroll: "yftNHFBQi",
};
var humanReadableEnumMap1 = {
	Bottom: "bottom",
	Left: "left",
	Right: "right",
	Top: "top",
};
var getProps2 = ({
	direction,
	gap,
	height,
	id,
	image01,
	image02,
	image03,
	image04,
	image05,
	image06,
	image07,
	image08,
	image09,
	showImage01,
	showImage02,
	showImage03,
	showImage04,
	showImage05,
	showImage06,
	showImage07,
	showImage08,
	showImage09,
	tickerVariant,
	width,
	...props
}) => {
	return {
		...props,
		AAIUBlnjH: showImage06 ?? props.AAIUBlnjH ?? true,
		B6DipibwS: image03 ??
			props.B6DipibwS ?? {
				alt: "Mailchimp logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/vEwVsUctVIZOnnUDjiFAZnBfQ0.svg?width=76&height=76",
			},
		cGM4xaeWB: image02 ??
			props.cGM4xaeWB ?? {
				alt: "Linear.app logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/WZBieSq9HMlZV6YHFeHuWZrubY.svg?width=76&height=76",
			},
		E3WDbY222: showImage09 ?? props.E3WDbY222 ?? true,
		EYavEvqbk: showImage05 ?? props.EYavEvqbk ?? true,
		ff8eyTPGY: image07 ??
			props.ff8eyTPGY ?? {
				alt: "Loom logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/PQwDHpHHo6LkBn288aRKPox3tY.svg?width=76&height=76",
			},
		GdHWaZGzc: image04 ??
			props.GdHWaZGzc ?? {
				alt: "Confluence logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/rIwx0YXJUHFQJwp5wOOGPGDHtfg.svg?width=76&height=76",
			},
		h_i5aqoI6: image05 ??
			props.h_i5aqoI6 ?? {
				alt: "Zapier logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/7z8nIe5VNDZRfkorYvrXVIwyKac.svg?width=76&height=76",
			},
		HzEsm26Xx: image01 ??
			props.HzEsm26Xx ?? {
				alt: "Asana logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/JzxexaeJ1VrTA2beNFkJv1XxAU.svg?width=76&height=76",
			},
		j2QckImb9: showImage04 ?? props.j2QckImb9 ?? true,
		llMGit0d0: showImage07 ?? props.llMGit0d0 ?? true,
		m9SGTYfPp: showImage01 ?? props.m9SGTYfPp ?? true,
		ma9v2jUiv:
			humanReadableEnumMap[tickerVariant] ??
			tickerVariant ??
			props.ma9v2jUiv ??
			"yftNHFBQi",
		opnqhcrQU: image09 ??
			props.opnqhcrQU ?? {
				alt: "Spectrum logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/3KGY9KbY0xx6nriJohA0sGcmC80.svg?width=76&height=76",
			},
		q8z6dJm7G: image06 ??
			props.q8z6dJm7G ?? {
				alt: "Slack logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/G0nzyLwjIqnhroSjOYxRMDHQ0dI.svg?width=76&height=76",
			},
		Qv5ilvWEJ: showImage02 ?? props.Qv5ilvWEJ ?? true,
		uEUZGvmj9: showImage08 ?? props.uEUZGvmj9 ?? true,
		ulyne2qTp: gap ?? props.ulyne2qTp ?? 16,
		VODWXLWc1:
			humanReadableEnumMap1[direction] ??
			direction ??
			props.VODWXLWc1 ??
			"left",
		VtWs6ORb_: image08 ??
			props.VtWs6ORb_ ?? {
				alt: "Google Meet logo",
				pixelHeight: 76,
				pixelWidth: 76,
				src: "https://framerusercontent.com/images/CETEJNIiyGnwauuXU1kWh7qEVg.svg?width=76&height=76",
			},
		YjoBQIGsw: showImage03 ?? props.YjoBQIGsw ?? true,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className,
		layoutId,
		variant,
		ma9v2jUiv,
		VODWXLWc1,
		ulyne2qTp,
		m9SGTYfPp,
		HzEsm26Xx,
		Qv5ilvWEJ,
		cGM4xaeWB,
		YjoBQIGsw,
		B6DipibwS,
		j2QckImb9,
		GdHWaZGzc,
		EYavEvqbk,
		h_i5aqoI6,
		AAIUBlnjH,
		q8z6dJm7G,
		llMGit0d0,
		ff8eyTPGY,
		uEUZGvmj9,
		VtWs6ORb_,
		E3WDbY222,
		opnqhcrQU,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "KrdgdKYgh",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const visible = equals(ma9v2jUiv, "yftNHFBQi");
	return (
		<LayoutGroup3
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants2
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition2 suppressHydrationWarning={true} value={transition12}>
					<motion3.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-visix6",
							className,
							classNames,
						)}
						data-framer-name={"Ticker"}
						layoutDependency={layoutDependency}
						layoutId={"KrdgdKYgh"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						{visible && (
							<ComponentViewportProvider suppressHydrationWarning={true}>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1rwv6nb-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"E2VmMrESD-container"}
									nodeId={"E2VmMrESD"}
									rendersWithMotion={true}
									scopeId={"VE7jZqmTQ"}
								>
									<VirtualScrollTicker
										suppressHydrationWarning={true}
										alignment={"center"}
										direction={VODWXLWc1}
										fadeOptions={{
											fadeAlpha: 0,
											fadeContent: true,
											fadeInset: 0,
											fadeWidth: 25,
											overflow: false,
										}}
										gap={ulyne2qTp}
										height={"100%"}
										id={"E2VmMrESD"}
										layoutId={"E2VmMrESD"}
										padding={0}
										paddingBottom={0}
										paddingLeft={0}
										paddingPerSide={false}
										paddingRight={0}
										paddingTop={0}
										sizingOptions={{
											heightType: true,
											widthType: true,
										}}
										slots={[
											m9SGTYfPp && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 425,
														intrinsicWidth: 320,
														pixelHeight: 850,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(HzEsm26Xx),
													}}
													className={"framer-15lmhsb"}
													data-framer-name={"Image 1"}
													layoutDependency={layoutDependency}
													layoutId={"aMloA2Imf"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											Qv5ilvWEJ && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 537.5,
														intrinsicWidth: 320,
														pixelHeight: 1075,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(cGM4xaeWB),
													}}
													className={"framer-1x19xxg"}
													data-framer-name={"Image 2"}
													layoutDependency={layoutDependency}
													layoutId={"wfkUdDqsb"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											YjoBQIGsw && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 571,
														intrinsicWidth: 320,
														pixelHeight: 1142,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(B6DipibwS),
													}}
													className={"framer-nu5v9f"}
													data-framer-name={"Image 3"}
													layoutDependency={layoutDependency}
													layoutId={"SOhoFy_9N"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											j2QckImb9 && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 640,
														intrinsicWidth: 320,
														pixelHeight: 1280,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(GdHWaZGzc),
													}}
													className={"framer-1ahfkhq"}
													data-framer-name={"Image 4"}
													layoutDependency={layoutDependency}
													layoutId={"KcGFIsqU1"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											EYavEvqbk && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 480,
														intrinsicWidth: 320,
														pixelHeight: 960,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(h_i5aqoI6),
													}}
													className={"framer-1l8bfwg"}
													data-framer-name={"Image 5"}
													layoutDependency={layoutDependency}
													layoutId={"mS9Usi3N4"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											AAIUBlnjH && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 571,
														intrinsicWidth: 320,
														pixelHeight: 1142,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(q8z6dJm7G),
													}}
													className={"framer-1n7hxu3"}
													data-framer-name={"Image 6"}
													layoutDependency={layoutDependency}
													layoutId={"fekbgESuS"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											llMGit0d0 && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 571,
														intrinsicWidth: 320,
														pixelHeight: 1142,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(ff8eyTPGY),
													}}
													className={"framer-yxuvuf"}
													data-framer-name={"Image 7"}
													layoutDependency={layoutDependency}
													layoutId={"LUMRvK6IA"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											uEUZGvmj9 && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 571,
														intrinsicWidth: 320,
														pixelHeight: 366,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(VtWs6ORb_),
													}}
													className={"framer-1k49v3l"}
													data-framer-name={"Image 8"}
													layoutDependency={layoutDependency}
													layoutId={"dWNsXBxmZ"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
											E3WDbY222 && (
												<Image
													suppressHydrationWarning={true}
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 571,
														intrinsicWidth: 320,
														pixelHeight: 1422,
														pixelWidth: 640,
														sizes: "76px",
														...toResponsiveImage(opnqhcrQU),
													}}
													className={"framer-y5rxbr"}
													data-framer-name={"Image 9"}
													layoutDependency={layoutDependency}
													layoutId={"MQ1_GJYBD"}
													style={{
														borderBottomLeftRadius: 16,
														borderBottomRightRadius: 16,
														borderTopLeftRadius: 16,
														borderTopRightRadius: 16,
													}}
												/>
											),
										]}
										speed={0.1}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion3.div>
				</Transition2>
			</Variants2>
		</LayoutGroup3>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Xxntd.framer-l73min, .framer-Xxntd .framer-l73min { display: block; }",
	".framer-Xxntd.framer-visix6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 76px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 588px; }",
	".framer-Xxntd .framer-1rwv6nb-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; }",
	".framer-Xxntd .framer-15lmhsb, .framer-Xxntd .framer-1x19xxg, .framer-Xxntd .framer-nu5v9f, .framer-Xxntd .framer-1ahfkhq, .framer-Xxntd .framer-1l8bfwg, .framer-Xxntd .framer-1n7hxu3, .framer-Xxntd .framer-yxuvuf, .framer-Xxntd .framer-1k49v3l, .framer-Xxntd .framer-y5rxbr { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 76px); overflow: visible; position: relative; width: 76px; }",
];
var FramerVE7jZqmTQ = withCSS2(Component2, css2, "framer-Xxntd");
var stdin_default2 = FramerVE7jZqmTQ;
FramerVE7jZqmTQ.displayName = "Integrations Ticker";
FramerVE7jZqmTQ.defaultProps = {
	height: 76,
	width: 588,
};
addPropertyControls3(FramerVE7jZqmTQ, {
	ma9v2jUiv: {
		defaultValue: "yftNHFBQi",
		description: "Animate automatically or on scroll?",
		options: ["yftNHFBQi", "fhgdpkffP"],
		optionTitles: ["Scroll", "Moving"],
		title: "Ticker Variant",
		type: ControlType3.Enum,
	},
	VODWXLWc1: TickerScrollControls?.["direction"] && {
		...TickerScrollControls["direction"],
		defaultValue: "left",
		description: void 0,
		hidden: void 0,
		title: "Direction",
	},
	ulyne2qTp: {
		defaultValue: 16,
		title: "Gap",
		type: ControlType3.Number,
	},
	m9SGTYfPp: {
		defaultValue: true,
		title: "Show Image 01",
		type: ControlType3.Boolean,
	},
	HzEsm26Xx: {
		__defaultAssetReference:
			"data:framer/asset-reference,JzxexaeJ1VrTA2beNFkJv1XxAU.svg?originalFilename=Asana.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Asana logo",
			assetReference:
				"data:framer/asset-reference,JzxexaeJ1VrTA2beNFkJv1XxAU.svg?originalFilename=Asana.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 01",
		type: ControlType3.ResponsiveImage,
	},
	Qv5ilvWEJ: {
		defaultValue: true,
		title: "Show Image 02",
		type: ControlType3.Boolean,
	},
	cGM4xaeWB: {
		__defaultAssetReference:
			"data:framer/asset-reference,WZBieSq9HMlZV6YHFeHuWZrubY.svg?originalFilename=Linear.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Linear.app logo",
			assetReference:
				"data:framer/asset-reference,WZBieSq9HMlZV6YHFeHuWZrubY.svg?originalFilename=Linear.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 02",
		type: ControlType3.ResponsiveImage,
	},
	YjoBQIGsw: {
		defaultValue: true,
		title: "Show Image 03",
		type: ControlType3.Boolean,
	},
	B6DipibwS: {
		__defaultAssetReference:
			"data:framer/asset-reference,vEwVsUctVIZOnnUDjiFAZnBfQ0.svg?originalFilename=Mail+Chimp.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Mailchimp logo",
			assetReference:
				"data:framer/asset-reference,vEwVsUctVIZOnnUDjiFAZnBfQ0.svg?originalFilename=Mail+Chimp.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 03",
		type: ControlType3.ResponsiveImage,
	},
	j2QckImb9: {
		defaultValue: true,
		title: "Show Image 04",
		type: ControlType3.Boolean,
	},
	GdHWaZGzc: {
		__defaultAssetReference:
			"data:framer/asset-reference,rIwx0YXJUHFQJwp5wOOGPGDHtfg.svg?originalFilename=Confluence.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Confluence logo",
			assetReference:
				"data:framer/asset-reference,rIwx0YXJUHFQJwp5wOOGPGDHtfg.svg?originalFilename=Confluence.svg&preferredSize=auto&width=76&height=76",
		},
		description: "",
		title: "Image 04",
		type: ControlType3.ResponsiveImage,
	},
	EYavEvqbk: {
		defaultValue: true,
		title: "Show Image 05",
		type: ControlType3.Boolean,
	},
	h_i5aqoI6: {
		__defaultAssetReference:
			"data:framer/asset-reference,7z8nIe5VNDZRfkorYvrXVIwyKac.svg?originalFilename=Zapier.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Zapier logo",
			assetReference:
				"data:framer/asset-reference,7z8nIe5VNDZRfkorYvrXVIwyKac.svg?originalFilename=Zapier.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 05",
		type: ControlType3.ResponsiveImage,
	},
	AAIUBlnjH: {
		defaultValue: true,
		title: "Show Image 06",
		type: ControlType3.Boolean,
	},
	q8z6dJm7G: {
		__defaultAssetReference:
			"data:framer/asset-reference,G0nzyLwjIqnhroSjOYxRMDHQ0dI.svg?originalFilename=Slack.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Slack logo",
			assetReference:
				"data:framer/asset-reference,G0nzyLwjIqnhroSjOYxRMDHQ0dI.svg?originalFilename=Slack.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 06",
		type: ControlType3.ResponsiveImage,
	},
	llMGit0d0: {
		defaultValue: true,
		title: "Show Image 07",
		type: ControlType3.Boolean,
	},
	ff8eyTPGY: {
		__defaultAssetReference:
			"data:framer/asset-reference,PQwDHpHHo6LkBn288aRKPox3tY.svg?originalFilename=Loom.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Loom logo",
			assetReference:
				"data:framer/asset-reference,PQwDHpHHo6LkBn288aRKPox3tY.svg?originalFilename=Loom.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 07",
		type: ControlType3.ResponsiveImage,
	},
	uEUZGvmj9: {
		defaultValue: true,
		title: "Show Image 08",
		type: ControlType3.Boolean,
	},
	VtWs6ORb_: {
		__defaultAssetReference:
			"data:framer/asset-reference,CETEJNIiyGnwauuXU1kWh7qEVg.svg?originalFilename=Meet.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Google Meet logo",
			assetReference:
				"data:framer/asset-reference,CETEJNIiyGnwauuXU1kWh7qEVg.svg?originalFilename=Meet.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 08",
		type: ControlType3.ResponsiveImage,
	},
	E3WDbY222: {
		defaultValue: true,
		title: "Show Image 09",
		type: ControlType3.Boolean,
	},
	opnqhcrQU: {
		__defaultAssetReference:
			"data:framer/asset-reference,3KGY9KbY0xx6nriJohA0sGcmC80.svg?originalFilename=Ioono.svg&preferredSize=auto&width=76&height=76",
		__vekterDefault: {
			alt: "Spectrum logo",
			assetReference:
				"data:framer/asset-reference,3KGY9KbY0xx6nriJohA0sGcmC80.svg?originalFilename=Ioono.svg&preferredSize=auto&width=76&height=76",
		},
		title: "Image 09",
		type: ControlType3.ResponsiveImage,
	},
});
addFonts2(
	FramerVE7jZqmTQ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TickerScrollFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:integrations-ticker
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IntegrationsTickerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var integrations_ticker_default = ComponentWithRoot;
export { integrations_ticker_default as default };
