// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Annual - Desktop' | ' Monthly - Desktop' | 'Annual - Mobile' | 'Monthly - Mobile' // Variant
 * direction?: 'Horizontal' | 'Vertical' // Direction
}} Props

 */
import { stdin_default } from "./chunks/chunk-DZTAFWBT.js";
import "./chunks/chunk-XKU2YJUW.js";
import "./chunks/chunk-3G7HFN4Q.js";
import "./chunks/chunk-KZKBIQL7.js";
import "./chunks/chunk-KGAIBNJG.js";
import "./chunks/chunk-ESTNRGIO.js";
import "./chunks/chunk-MDOKQI4I.js";
import "./chunks/chunk-S3YIMS7I.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:main-cards
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vh3DZNRWPOZMHRrHaT6N/IfcVy2IL2EHGV9cItnbW/aSVT7nMKA.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PricingCardFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["OgoqHVctW", "WYzLZfyiV", "z59T85cx8", "xKI5LXHMn"];
var serializationHash = "framer-YFCgY";
var variantClassNames = {
	OgoqHVctW: "framer-v-w8o3q2",
	WYzLZfyiV: "framer-v-1gbe244",
	xKI5LXHMn: "framer-v-j9earn",
	z59T85cx8: "framer-v-1ppahwq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 64,
};
var transition2 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 80,
};
var transition3 = {
	damping: 30,
	delay: 0.1,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 96,
};
var transition4 = {
	damping: 30,
	delay: 0.2,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	Horizontal: "row",
	Vertical: "column",
};
var humanReadableVariantMap = {
	" Monthly - Desktop": "WYzLZfyiV",
	"Annual - Desktop": "OgoqHVctW",
	"Annual - Mobile": "z59T85cx8",
	"Monthly - Mobile": "xKI5LXHMn",
};
var getProps = ({ direction, height, id, width, ...props }) => {
	return {
		...props,
		ieNAEbdsi:
			humanReadableEnumMap[direction] ?? direction ?? props.ieNAEbdsi ?? "row",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "OgoqHVctW",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		ieNAEbdsi: ieNAEbdsi2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "OgoqHVctW",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const nDAP3_ae61tfcs5w = activeVariantCallback(async (...args) => {
		setVariant("WYzLZfyiV");
	});
	const nDAP3_ae61tv0kd0 = activeVariantCallback(async (...args) => {
		setVariant("OgoqHVctW");
	});
	const nDAP3_ae618my98a = activeVariantCallback(async (...args) => {
		setVariant("xKI5LXHMn");
	});
	const nDAP3_ae61404935 = activeVariantCallback(async (...args) => {
		setVariant("z59T85cx8");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-w8o3q2",
							className,
							classNames,
						)}
						data-framer-name={"Annual - Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"OgoqHVctW"}
						ref={refBinding}
						style={{
							"--dp4a0x": ieNAEbdsi2 === "column" ? "100%" : "1px",
							"--itcjnr": ieNAEbdsi2,
							"--sez5ub": ieNAEbdsi2 === "column" ? void 0 : "1 0 0px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								WYzLZfyiV: {
									"data-framer-name": " Monthly - Desktop",
								},
								xKI5LXHMn: {
									"data-framer-name": "Monthly - Mobile",
								},
								z59T85cx8: {
									"data-framer-name": "Annual - Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={498}
							width={
								ieNAEbdsi2 === "row"
									? `max((${componentViewport?.width || "100vw"} - 48px) / 3, 1px)`
									: componentViewport?.width || "100vw"
							}
							{...addPropertyOverrides(
								{
									xKI5LXHMn: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1607) - 0 - 1542) / 2 +
												0 +
												0),
									},
									z59T85cx8: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1609) - 0 - 1542) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								suppressHydrationWarning={true}
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-19ej1a4-container"}
								layoutDependency={layoutDependency}
								layoutId={"AMAL_C7GS-container"}
								nodeId={"AMAL_C7GS"}
								rendersWithMotion={true}
								scopeId={"aSVT7nMKA"}
								{...addPropertyOverrides(
									{
										xKI5LXHMn: {
											__framer__styleAppearEffectEnabled: void 0,
										},
										z59T85cx8: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									D5QmKxhRV: "Free",
									height: "100%",
									HWBaxxLnK: "Unlimited projects",
									id: "AMAL_C7GS",
									jeXkTVk6E: "Time tracking",
									kWHVVUGpC: "wICn05UoA",
									layoutId: "AMAL_C7GS",
									OYVPGB9pZ: "b3g41sUz1",
									r4zR35OfY: "CRM",
									RwX7DRU88: "Try Freelio free",
									Sn20WctUb: "iOS & Andriod app",
									SrSRuhSEK: "Unlimited clients",
									style: {
										width: "100%",
									},
									sVLxfDlNH: "Dreelio Basic",
									unoYLUCPT: false,
									variant: "MoSzX5N3N",
									width: "100%",
									y4RQGWuBU: "For solo use with light needs.",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={498}
							width={
								ieNAEbdsi2 === "row"
									? `max((${componentViewport?.width || "100vw"} - 48px) / 3, 1px)`
									: componentViewport?.width || "100vw"
							}
							{...addPropertyOverrides(
								{
									xKI5LXHMn: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1607) - 0 - 1542) / 2 +
												498 +
												24),
									},
									z59T85cx8: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1609) - 0 - 1542) / 2 +
												498 +
												24),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								suppressHydrationWarning={true}
								__framer__animate={{
									transition: transition3,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation2}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1cuslo7-container"}
								layoutDependency={layoutDependency}
								layoutId={"dZuD6vJWf-container"}
								nodeId={"dZuD6vJWf"}
								rendersWithMotion={true}
								scopeId={"aSVT7nMKA"}
								{...addPropertyOverrides(
									{
										xKI5LXHMn: {
											__framer__styleAppearEffectEnabled: void 0,
										},
										z59T85cx8: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									D5QmKxhRV: "$189/yr",
									height: "100%",
									HWBaxxLnK: "Everything in Basic",
									id: "dZuD6vJWf",
									jeXkTVk6E: "Expense tracking",
									kWHVVUGpC: "wICn05UoA",
									layoutId: "dZuD6vJWf",
									nDAP3_ae6: nDAP3_ae61tfcs5w,
									OYVPGB9pZ: "b3g41sUz1",
									r4zR35OfY: "Income tracking",
									RwX7DRU88: "Try Freelio free",
									Sn20WctUb: "Scheduling",
									SrSRuhSEK: "Invoices & payments",
									style: {
										width: "100%",
									},
									sVLxfDlNH: "Dreelio Premium",
									unoYLUCPT: true,
									variant: "GcJITsOdZ",
									width: "100%",
									y4RQGWuBU: "For pro use with light needs.",
									...addPropertyOverrides(
										{
											WYzLZfyiV: {
												D5QmKxhRV: "$87/mo",
												kWHVVUGpC: "jAmzGgxnP",
												nDAP3_ae6: nDAP3_ae61tv0kd0,
												OYVPGB9pZ: "ndcVLqBeZ",
												unoYLUCPT: false,
											},
											xKI5LXHMn: {
												D5QmKxhRV: "$87/mo",
												kWHVVUGpC: "iaupWKNUK",
												nDAP3_ae6: nDAP3_ae61404935,
												OYVPGB9pZ: "ndcVLqBeZ",
												unoYLUCPT: false,
											},
											z59T85cx8: {
												kWHVVUGpC: "zcvXeLxCv",
												nDAP3_ae6: nDAP3_ae618my98a,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={498}
							width={
								ieNAEbdsi2 === "row"
									? `max((${componentViewport?.width || "100vw"} - 48px) / 3, 1px)`
									: componentViewport?.width || "100vw"
							}
							{...addPropertyOverrides(
								{
									xKI5LXHMn: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1607) - 0 - 1542) / 2 +
												996 +
												48),
									},
									z59T85cx8: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1609) - 0 - 1542) / 2 +
												996 +
												48),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								suppressHydrationWarning={true}
								__framer__animate={{
									transition: transition4,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation3}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-8018o2-container"}
								layoutDependency={layoutDependency}
								layoutId={"ipRjSJNks-container"}
								nodeId={"ipRjSJNks"}
								rendersWithMotion={true}
								scopeId={"aSVT7nMKA"}
								{...addPropertyOverrides(
									{
										xKI5LXHMn: {
											__framer__styleAppearEffectEnabled: void 0,
										},
										z59T85cx8: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									D5QmKxhRV: "Flexible",
									height: "100%",
									HWBaxxLnK: "Everything in Premium",
									id: "ipRjSJNks",
									jeXkTVk6E: "Advanced onboarding",
									kWHVVUGpC: "wICn05UoA",
									layoutId: "ipRjSJNks",
									OYVPGB9pZ: "b3g41sUz1",
									r4zR35OfY: "Hubspot integration",
									RwX7DRU88: "Contact sales",
									Sn20WctUb: "Timesheets",
									SrSRuhSEK: "Custom data import",
									style: {
										width: "100%",
									},
									sVLxfDlNH: "Dreelio Enterprise",
									unoYLUCPT: false,
									variant: "MoSzX5N3N",
									width: "100%",
									y4RQGWuBU: "For team use with light needs.",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YFCgY.framer-1lca7xo, .framer-YFCgY .framer-1lca7xo { display: block; }",
	".framer-YFCgY.framer-w8o3q2 { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: var(--itcjnr); flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1072px; }",
	".framer-YFCgY .framer-19ej1a4-container, .framer-YFCgY .framer-1cuslo7-container, .framer-YFCgY .framer-8018o2-container { flex: var(--sez5ub); height: auto; position: relative; width: var(--dp4a0x); }",
	".framer-YFCgY.framer-v-1ppahwq.framer-w8o3q2, .framer-YFCgY.framer-v-j9earn.framer-w8o3q2 { flex-direction: column; width: 390px; }",
	".framer-YFCgY.framer-v-1ppahwq .framer-19ej1a4-container, .framer-YFCgY.framer-v-1ppahwq .framer-1cuslo7-container, .framer-YFCgY.framer-v-1ppahwq .framer-8018o2-container, .framer-YFCgY.framer-v-j9earn .framer-19ej1a4-container, .framer-YFCgY.framer-v-j9earn .framer-1cuslo7-container, .framer-YFCgY.framer-v-j9earn .framer-8018o2-container { flex: none; width: 100%; }",
];
var FrameraSVT7nMKA = withCSS(Component, css, "framer-YFCgY");
var stdin_default2 = FrameraSVT7nMKA;
FrameraSVT7nMKA.displayName = "Main Cards";
FrameraSVT7nMKA.defaultProps = {
	height: 581,
	width: 1072,
};
addPropertyControls(FrameraSVT7nMKA, {
	variant: {
		options: ["OgoqHVctW", "WYzLZfyiV", "z59T85cx8", "xKI5LXHMn"],
		optionTitles: [
			"Annual - Desktop",
			" Monthly - Desktop",
			"Annual - Mobile",
			"Monthly - Mobile",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	ieNAEbdsi: {
		defaultValue: "row",
		displaySegmentedControl: true,
		optionIcons: ["direction-horizontal", "direction-vertical"],
		options: ["row", "column"],
		optionTitles: ["Horizontal", "Vertical"],
		title: "Direction",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameraSVT7nMKA,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...PricingCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:main-cards
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "z59T85cx8",
	xl: "OgoqHVctW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainCardsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var main_cards_default = ComponentWithRoot;
export { main_cards_default as default };
