// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary' | 'Secondary' | 'Tertiary' // Variant
 * title?: string // Title
 * link?: string // Link
 * border?: any // Border
 * click?: Function // Click
 * teriraryButtonText?: string // Terirary Button Text
}} Props

 */
import { stdin_default } from "./chunks/chunk-KGAIBNJG.js";
import "./chunks/chunk-ESTNRGIO.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:main-button
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "OBWsuGAEJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var main_button_default = ComponentWithRoot;
export { main_button_default as default };
