// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop - Primary' | 'Desktop - On Scroll' | 'Mobile - Close' | 'Mobile - Open' // Variant
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-UXS7KTTN.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-4W7W2DTS.js";
import "./chunks/chunk-7XAY5VTW.js";
import { stdin_default } from "./chunks/chunk-SODYEVIK.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-KGAIBNJG.js";
import "./chunks/chunk-ESTNRGIO.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:nav-bar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iRSKJuNn7WXnegSOvTxy/iEqswWz4axkdCbaBl9Ea/Da7zCedh0.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ComponentLogoFonts = getFonts(stdin_default);
var BurgerMenuFonts = getFonts(stdin_default2);
var NavBarItemFonts = getFonts(stdin_default4);
var MainButtonFonts = getFonts(stdin_default3);
var cycleOrder = ["vOq4aLnBp", "LScJxvL1r", "BdtzNLOPu", "CiFR086H3"];
var serializationHash = "framer-9XGmo";
var variantClassNames = {
	BdtzNLOPu: "framer-v-snyvu4",
	CiFR086H3: "framer-v-49dy3n",
	LScJxvL1r: "framer-v-1xunle3",
	vOq4aLnBp: "framer-v-1pd96co",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop - On Scroll": "LScJxvL1r",
	"Desktop - Primary": "vOq4aLnBp",
	"Mobile - Close": "BdtzNLOPu",
	"Mobile - Open": "CiFR086H3",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "vOq4aLnBp",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "vOq4aLnBp",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const GsV0XqZB57419pp = activeVariantCallback(async (...args) => {
		setVariant("xK_NMMJ3m");
	});
	const GsV0XqZB510wo7r5 = activeVariantCallback(async (...args) => {
		setVariant("CiFR086H3");
	});
	const GsV0XqZB51j2li9b = activeVariantCallback(async (...args) => {
		setVariant("BdtzNLOPu");
	});
	const UWmuLqfij1j2li9b = activeVariantCallback(async (...args) => {
		setVariant("BdtzNLOPu");
	});
	const OnuyxJuml1j2li9b = activeVariantCallback(async (...args) => {
		setVariant("BdtzNLOPu");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["BdtzNLOPu", "CiFR086H3"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["BdtzNLOPu", "CiFR086H3"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed2 = () => {
		if (baseVariant === "CiFR086H3") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.nav
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1pd96co",
							className,
							classNames,
						)}
						data-framer-name={"Desktop - Primary"}
						layoutDependency={layoutDependency}
						layoutId={"vOq4aLnBp"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						{...addPropertyOverrides(
							{
								BdtzNLOPu: {
									"data-framer-name": "Mobile - Close",
								},
								CiFR086H3: {
									"data-framer-name": "Mobile - Open",
								},
								LScJxvL1r: {
									"data-framer-name": "Desktop - On Scroll",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1gs8anj"}
							data-border={true}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"Llnma7Iyu"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(117, 115, 114, 0)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backdropFilter: "blur(0px)",
								backgroundColor: "rgba(255, 255, 255, 0)",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
								boxShadow: "none",
								WebkitBackdropFilter: "blur(0px)",
							}}
							variants={{
								BdtzNLOPu: {
									"--border-color": "rgba(117, 115, 114, 0.15)",
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(255, 255, 255, 0.25)",
									WebkitBackdropFilter: "blur(10px)",
								},
								CiFR086H3: {
									"--border-color": "rgba(117, 115, 114, 0.15)",
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(255, 255, 255, 0.5)",
									borderBottomLeftRadius: 32,
									borderBottomRightRadius: 32,
									borderTopLeftRadius: 32,
									borderTopRightRadius: 32,
									boxShadow:
										"0px 0.6021873017743928px 0.6021873017743928px -0.8333333333333333px rgba(26, 22, 21, 0.08), 0px 2.288533303243457px 2.288533303243457px -1.6666666666666665px rgba(26, 22, 21, 0.08), 0px 10px 10px -2.5px rgba(26, 22, 21, 0.08)",
									WebkitBackdropFilter: "blur(10px)",
								},
								LScJxvL1r: {
									"--border-color": "rgba(117, 115, 114, 0.15)",
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(255, 255, 255, 0.25)",
									WebkitBackdropFilter: "blur(10px)",
								},
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1hzrb5k"}
								data-framer-name={"Logo Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"Llnma7IyunP0wfvP4A"}
							>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={24}
									y={
										(componentViewport?.y || 0) +
										(16 + ((componentViewport?.height || 103) - 32 - 71) / 2) +
										23.5 +
										0
									}
									{...addPropertyOverrides(
										{
											BdtzNLOPu: {
												y:
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 96) - 32 - 64) / 2) +
													8 +
													0 +
													12,
											},
											CiFR086H3: {
												y: (componentViewport?.y || 0) + 16 + 0 + 8 + 0 + 12,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1sxypvp-container"}
										layoutDependency={layoutDependency}
										layoutId={"Llnma7IyuS7C1Q9Un6-container"}
										nodeId={"Llnma7IyuS7C1Q9Un6"}
										rendersWithMotion={true}
										scopeId={"Da7zCedh0"}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "Llnma7IyuS7C1Q9Un6",
											layoutId: "Llnma7IyuS7C1Q9Un6",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								{isDisplayed() && (
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										{...addPropertyOverrides(
											{
												BdtzNLOPu: {
													height: 48,
													width: "48px",
													y:
														(componentViewport?.y || 0) +
														(16 +
															((componentViewport?.height || 96) - 32 - 64) /
																2) +
														8 +
														0 +
														0,
												},
												CiFR086H3: {
													height: 48,
													width: "48px",
													y: (componentViewport?.y || 0) + 16 + 0 + 8 + 0 + 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1soteil-container"}
											layoutDependency={layoutDependency}
											layoutId={"Llnma7IyuzmRYlznvL-container"}
											nodeId={"Llnma7IyuzmRYlznvL"}
											rendersWithMotion={true}
											scopeId={"Da7zCedh0"}
										>
											{_jsx(stdin_default2, {
												suppressHydrationWarning: true,
												GsV0XqZB5: GsV0XqZB57419pp,
												height: "100%",
												id: "Llnma7IyuzmRYlznvL",
												layoutId: "Llnma7IyuzmRYlznvL",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: "zKZ3lPU_M",
												width: "100%",
												...addPropertyOverrides(
													{
														BdtzNLOPu: {
															GsV0XqZB5: GsV0XqZB510wo7r5,
														},
														CiFR086H3: {
															GsV0XqZB5: GsV0XqZB51j2li9b,
															variant: "h7_3plj7K",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</motion.div>
							{isDisplayed1() && (
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1g0xg9f"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"Llnma7IyunmtO88aZI"}
								>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													hash: ":VMJGhIahi",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":VMJGhIahi",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												y={
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 103) - 32 - 71) /
															2) +
													15.5 +
													0
												}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-ilglct-container"}
													layoutDependency={layoutDependency}
													layoutId={"XUBQNtDPQ-container"}
													nodeId={"XUBQNtDPQ"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "XUBQNtDPQ",
														Imo9x9KdN: resolvedLinks[0],
														jzvVRsWJU: "Features",
														layoutId: "XUBQNtDPQ",
														uH_gmM4qY: false,
														width: "100%",
														...addPropertyOverrides(
															{
																LScJxvL1r: {
																	Imo9x9KdN: resolvedLinks[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													hash: ":kO4oh9IU1",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":kO4oh9IU1",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												y={
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 103) - 32 - 71) /
															2) +
													15.5 +
													0
												}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-1bsfg90-container"}
													layoutDependency={layoutDependency}
													layoutId={"BPZ7ZYI86-container"}
													nodeId={"BPZ7ZYI86"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "BPZ7ZYI86",
														Imo9x9KdN: resolvedLinks1[0],
														jzvVRsWJU: "Benefits",
														layoutId: "BPZ7ZYI86",
														uH_gmM4qY: false,
														width: "100%",
														...addPropertyOverrides(
															{
																LScJxvL1r: {
																	Imo9x9KdN: resolvedLinks1[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													hash: ":g7Iswtddg",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":g7Iswtddg",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks2) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												y={
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 103) - 32 - 71) /
															2) +
													15.5 +
													0
												}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-d52vd2-container"}
													layoutDependency={layoutDependency}
													layoutId={"QsajWYqbQ-container"}
													nodeId={"QsajWYqbQ"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "QsajWYqbQ",
														Imo9x9KdN: resolvedLinks2[0],
														jzvVRsWJU: "Pricing",
														layoutId: "QsajWYqbQ",
														uH_gmM4qY: false,
														width: "100%",
														...addPropertyOverrides(
															{
																LScJxvL1r: {
																	Imo9x9KdN: resolvedLinks2[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													webPageId: "otG8ouHU2",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "otG8ouHU2",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks3) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												y={
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 103) - 32 - 71) /
															2) +
													15.5 +
													0
												}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-1fnrdo2-container"}
													layoutDependency={layoutDependency}
													layoutId={"l_tw9DvYG-container"}
													nodeId={"l_tw9DvYG"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "l_tw9DvYG",
														Imo9x9KdN: resolvedLinks3[0],
														jzvVRsWJU: "Blog",
														layoutId: "l_tw9DvYG",
														uH_gmM4qY: false,
														width: "100%",
														...addPropertyOverrides(
															{
																LScJxvL1r: {
																	Imo9x9KdN: resolvedLinks3[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													webPageId: "XzDpWUuVS",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "XzDpWUuVS",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks4) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												y={
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 103) - 32 - 71) /
															2) +
													15.5 +
													0
												}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-em0091-container"}
													layoutDependency={layoutDependency}
													layoutId={"lSML4sLgz-container"}
													nodeId={"lSML4sLgz"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "lSML4sLgz",
														Imo9x9KdN: resolvedLinks4[0],
														jzvVRsWJU: "Contact Us",
														layoutId: "lSML4sLgz",
														uH_gmM4qY: false,
														width: "100%",
														...addPropertyOverrides(
															{
																LScJxvL1r: {
																	Imo9x9KdN: resolvedLinks4[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.div>
							)}
							{isDisplayed1() && (
								<ResolveLinks
									suppressHydrationWarning={true}
									links={[
										{
											href: {
												webPageId: "XzDpWUuVS",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "XzDpWUuVS",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks5) => (
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={55}
											y={
												(componentViewport?.y || 0) +
												(16 +
													((componentViewport?.height || 103) - 32 - 71) / 2) +
												8
											}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-1iaaojo-container"}
												layoutDependency={layoutDependency}
												layoutId={"Llnma7Iyusln30WG2Z-container"}
												nodeId={"Llnma7Iyusln30WG2Z"}
												rendersWithMotion={true}
												scopeId={"Da7zCedh0"}
											>
												{_jsx(stdin_default3, {
													suppressHydrationWarning: true,
													ektwzyaAy: "Try Dreelio free",
													FHCLGB0I0:
														"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
													height: "100%",
													id: "Llnma7Iyusln30WG2Z",
													layoutId: "Llnma7Iyusln30WG2Z",
													qomMPfTNC: {
														borderColor: "rgb(227, 225, 225)",
														borderStyle: "solid",
														borderWidth: 1,
													},
													variant: "OBWsuGAEJ",
													width: "100%",
													yPsg9PA2x: resolvedLinks5[0],
													...addPropertyOverrides(
														{
															LScJxvL1r: {
																yPsg9PA2x: resolvedLinks5[1],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							)}
						</motion.div>
						{isDisplayed2() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1riix9x"}
								data-border={true}
								data-framer-name={"Mobile Menu"}
								layoutDependency={layoutDependency}
								layoutId={"nU3VlCQcO"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(117, 115, 114, 0.15)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(255, 255, 255, 0.5)",
									borderBottomLeftRadius: 32,
									borderBottomRightRadius: 32,
									borderTopLeftRadius: 32,
									borderTopRightRadius: 32,
									boxShadow:
										"0px 0.6021873017743928px 0.6021873017743928px -0.8333333333333333px rgba(26, 22, 21, 0.08), 0px 2.288533303243457px 2.288533303243457px -1.6666666666666665px rgba(26, 22, 21, 0.08), 0px 10px 10px -2.5px rgba(26, 22, 21, 0.08)",
									WebkitBackdropFilter: "blur(10px)",
								}}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-whwofh"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"yD2wwwKSI"}
								>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													hash: ":VMJGhIahi",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":VMJGhIahi",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks6) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												{...addPropertyOverrides(
													{
														CiFR086H3: {
															width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
															y:
																(componentViewport?.y || 0) +
																16 +
																72 +
																16 +
																0 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-3gr670-container"}
													layoutDependency={layoutDependency}
													layoutId={"TTAMQLj7b-container"}
													nodeId={"TTAMQLj7b"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "TTAMQLj7b",
														Imo9x9KdN: resolvedLinks6[0],
														jzvVRsWJU: "Features",
														layoutId: "TTAMQLj7b",
														style: {
															width: "100%",
														},
														uH_gmM4qY: false,
														UWmuLqfij: UWmuLqfij1j2li9b,
														width: "100%",
														...addPropertyOverrides(
															{
																CiFR086H3: {
																	Imo9x9KdN: resolvedLinks6[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													hash: ":kO4oh9IU1",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":kO4oh9IU1",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks7) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												{...addPropertyOverrides(
													{
														CiFR086H3: {
															width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
															y:
																(componentViewport?.y || 0) +
																16 +
																72 +
																16 +
																0 +
																0 +
																48,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-18aw6h3-container"}
													layoutDependency={layoutDependency}
													layoutId={"bDE8PN0qj-container"}
													nodeId={"bDE8PN0qj"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "bDE8PN0qj",
														Imo9x9KdN: resolvedLinks7[0],
														jzvVRsWJU: "Benefits",
														layoutId: "bDE8PN0qj",
														style: {
															width: "100%",
														},
														uH_gmM4qY: false,
														UWmuLqfij: UWmuLqfij1j2li9b,
														width: "100%",
														...addPropertyOverrides(
															{
																CiFR086H3: {
																	Imo9x9KdN: resolvedLinks7[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													hash: ":g7Iswtddg",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":g7Iswtddg",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks8) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												{...addPropertyOverrides(
													{
														CiFR086H3: {
															width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
															y:
																(componentViewport?.y || 0) +
																16 +
																72 +
																16 +
																0 +
																0 +
																96,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-1ww13i0-container"}
													layoutDependency={layoutDependency}
													layoutId={"ZaBwndSwu-container"}
													nodeId={"ZaBwndSwu"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "ZaBwndSwu",
														Imo9x9KdN: resolvedLinks8[0],
														jzvVRsWJU: "Pricing",
														layoutId: "ZaBwndSwu",
														style: {
															width: "100%",
														},
														uH_gmM4qY: false,
														UWmuLqfij: UWmuLqfij1j2li9b,
														width: "100%",
														...addPropertyOverrides(
															{
																CiFR086H3: {
																	Imo9x9KdN: resolvedLinks8[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													webPageId: "otG8ouHU2",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "otG8ouHU2",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks9) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												{...addPropertyOverrides(
													{
														CiFR086H3: {
															width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
															y:
																(componentViewport?.y || 0) +
																16 +
																72 +
																16 +
																0 +
																0 +
																144,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-e3gzpb-container"}
													layoutDependency={layoutDependency}
													layoutId={"ti02leH_q-container"}
													nodeId={"ti02leH_q"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "ti02leH_q",
														Imo9x9KdN: resolvedLinks9[0],
														jzvVRsWJU: "Blog",
														layoutId: "ti02leH_q",
														style: {
															width: "100%",
														},
														uH_gmM4qY: false,
														UWmuLqfij: UWmuLqfij1j2li9b,
														width: "100%",
														...addPropertyOverrides(
															{
																CiFR086H3: {
																	Imo9x9KdN: resolvedLinks9[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										suppressHydrationWarning={true}
										links={[
											{
												href: {
													webPageId: "XzDpWUuVS",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "XzDpWUuVS",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks10) => (
											<ComponentViewportProvider
												suppressHydrationWarning={true}
												height={40}
												{...addPropertyOverrides(
													{
														CiFR086H3: {
															width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
															y:
																(componentViewport?.y || 0) +
																16 +
																72 +
																16 +
																0 +
																0 +
																192,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													suppressHydrationWarning={true}
													className={"framer-131tkcf-container"}
													layoutDependency={layoutDependency}
													layoutId={"a0oXd8_bc-container"}
													nodeId={"a0oXd8_bc"}
													rendersWithMotion={true}
													scopeId={"Da7zCedh0"}
												>
													{_jsx(stdin_default4, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "a0oXd8_bc",
														Imo9x9KdN: resolvedLinks10[0],
														jzvVRsWJU: "Contact Us",
														layoutId: "a0oXd8_bc",
														style: {
															width: "100%",
														},
														uH_gmM4qY: false,
														UWmuLqfij: UWmuLqfij1j2li9b,
														width: "100%",
														...addPropertyOverrides(
															{
																CiFR086H3: {
																	Imo9x9KdN: resolvedLinks10[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.div>
								<ResolveLinks
									suppressHydrationWarning={true}
									links={[
										{
											href: {
												webPageId: "XzDpWUuVS",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "XzDpWUuVS",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks11) => (
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={55}
											{...addPropertyOverrides(
												{
													CiFR086H3: {
														width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
														y: (componentViewport?.y || 0) + 16 + 72 + 16 + 264,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-pzj2lr-container"}
												layoutDependency={layoutDependency}
												layoutId={"m3_m7O1CC-container"}
												nodeId={"m3_m7O1CC"}
												rendersWithMotion={true}
												scopeId={"Da7zCedh0"}
											>
												{_jsx(stdin_default3, {
													suppressHydrationWarning: true,
													ektwzyaAy: "Try Dreelio free",
													FHCLGB0I0:
														"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
													height: "100%",
													id: "m3_m7O1CC",
													layoutId: "m3_m7O1CC",
													OnuyxJuml: OnuyxJuml1j2li9b,
													qomMPfTNC: {
														borderColor: "rgb(227, 225, 225)",
														borderStyle: "solid",
														borderWidth: 1,
													},
													style: {
														width: "100%",
													},
													variant: "OBWsuGAEJ",
													width: "100%",
													yPsg9PA2x: resolvedLinks11[0],
													...addPropertyOverrides(
														{
															CiFR086H3: {
																yPsg9PA2x: resolvedLinks11[1],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							</motion.div>
						)}
					</motion.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-9XGmo.framer-1l6mnn3, .framer-9XGmo .framer-1l6mnn3 { display: block; }",
	".framer-9XGmo.framer-1pd96co { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1072px; overflow: visible; padding: 16px; position: relative; width: 1072px; }",
	".framer-9XGmo .framer-1gs8anj { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 8px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-9XGmo .framer-1hzrb5k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-9XGmo .framer-1sxypvp-container, .framer-9XGmo .framer-ilglct-container, .framer-9XGmo .framer-1bsfg90-container, .framer-9XGmo .framer-d52vd2-container, .framer-9XGmo .framer-1fnrdo2-container, .framer-9XGmo .framer-em0091-container, .framer-9XGmo .framer-1iaaojo-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-9XGmo .framer-1soteil-container { flex: none; height: 48px; position: relative; width: 48px; }",
	".framer-9XGmo .framer-1g0xg9f { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-9XGmo .framer-1riix9x { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 16px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-9XGmo .framer-whwofh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 20px 0px; position: relative; width: 100%; }",
	".framer-9XGmo .framer-3gr670-container, .framer-9XGmo .framer-18aw6h3-container, .framer-9XGmo .framer-1ww13i0-container, .framer-9XGmo .framer-e3gzpb-container, .framer-9XGmo .framer-131tkcf-container, .framer-9XGmo .framer-pzj2lr-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-9XGmo.framer-v-1xunle3.framer-1pd96co { max-width: 834px; padding: 16px 0px 16px 0px; width: 834px; }",
	".framer-9XGmo.framer-v-1xunle3 .framer-1gs8anj { padding: 8px 8px 8px 24px; }",
	".framer-9XGmo.framer-v-snyvu4.framer-1pd96co { max-width: unset; padding: 16px 0px 16px 0px; width: 350px; }",
	".framer-9XGmo.framer-v-snyvu4 .framer-1gs8anj { flex-direction: column; gap: 12px; justify-content: flex-start; }",
	".framer-9XGmo.framer-v-snyvu4 .framer-1hzrb5k, .framer-9XGmo.framer-v-49dy3n .framer-1hzrb5k { gap: unset; justify-content: space-between; padding: 0px 0px 0px 8px; width: 100%; }",
	".framer-9XGmo.framer-v-49dy3n.framer-1pd96co { flex-direction: column; gap: 8px; justify-content: flex-start; max-width: unset; padding: 16px 0px 16px 0px; width: 350px; }",
	".framer-9XGmo.framer-v-49dy3n .framer-1gs8anj { flex: none; flex-direction: column; gap: 12px; justify-content: flex-start; width: 100%; }",
	".framer-9XGmo.framer-v-49dy3n .framer-1riix9x { flex: none; width: 100%; }",
	".framer-9XGmo.framer-v-49dy3n .framer-3gr670-container { order: 0; }",
	".framer-9XGmo.framer-v-49dy3n .framer-18aw6h3-container { order: 1; }",
	".framer-9XGmo.framer-v-49dy3n .framer-1ww13i0-container { order: 2; }",
	".framer-9XGmo.framer-v-49dy3n .framer-e3gzpb-container { order: 3; }",
	".framer-9XGmo.framer-v-49dy3n .framer-131tkcf-container { order: 4; }",
	'.framer-9XGmo[data-border="true"]::after, .framer-9XGmo [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerDa7zCedh0 = withCSS(Component, css, "framer-9XGmo");
var stdin_default5 = FramerDa7zCedh0;
FramerDa7zCedh0.displayName = "Nav Bar";
FramerDa7zCedh0.defaultProps = {
	height: 103,
	width: 1072,
};
addPropertyControls(FramerDa7zCedh0, {
	variant: {
		options: ["vOq4aLnBp", "LScJxvL1r", "BdtzNLOPu", "CiFR086H3"],
		optionTitles: [
			"Desktop - Primary",
			"Desktop - On Scroll",
			"Mobile - Close",
			"Mobile - Open",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerDa7zCedh0,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ComponentLogoFonts,
		...BurgerMenuFonts,
		...NavBarItemFonts,
		...MainButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-bar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavBarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var nav_bar_default = ComponentWithRoot;
export { nav_bar_default as default };
