// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1c5ad012f0be7154 "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * content?: string // Content
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * position?: string // Position
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-Y2HA6WRM.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-KZKBIQL7.js";
import { className, css, fonts } from "./chunks/chunk-7XAY5VTW.js";
import { routes } from "./chunks/chunk-ZTPEOF5B.js";

// virtual:reviews-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1iBHSNDfrFwwLv2GQYBZ/HHSEryg5qYZB02ptSwzD/ugDauJtmh.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["jpA_HH3dp", "NFPD0u5mY"];
var serializationHash = "framer-MxTqP";
var variantClassNames = {
	jpA_HH3dp: "framer-v-1a9oivf",
	NFPD0u5mY: "framer-v-1wlegg9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "jpA_HH3dp",
	Mobile: "NFPD0u5mY",
};
var getProps = ({
	content,
	height,
	id,
	image,
	name1,
	position,
	width,
	...props
}) => {
	return {
		...props,
		BUy0U2_Ht: position ?? props.BUy0U2_Ht ?? "Design Ops Lead, teamwork.",
		FrWUmwkt3: name1 ?? props.FrWUmwkt3 ?? "Leah Daniel",
		jk3RY9Xr3: image ?? props.jk3RY9Xr3,
		K3T_HZ6vw:
			content ??
			props.K3T_HZ6vw ??
			'"As a fast-moving design team, we needed a tool that matched our pace. From client onboarding to getting paid, this just works clean, fast, and beautifully built."',
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "jpA_HH3dp",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		K3T_HZ6vw,
		jk3RY9Xr3,
		FrWUmwkt3,
		BUy0U2_Ht,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "jpA_HH3dp",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1a9oivf",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"jpA_HH3dp"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(255, 255, 255, 0.7)",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
						{...addPropertyOverrides(
							{
								NFPD0u5mY: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-1mgldnr"}
							data-framer-name={
								"Keep every conversation in sync\u2014use comments, messages, channels, and project chats to stay on the same page"
							}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"fzhDj85z9"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={K3T_HZ6vw}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									suppressHydrationWarning={true}
									className={"framer-styles-preset-rsfkj"}
									data-styles-preset={"q2ShOlRIr"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
									}}
								>
									{
										'"As a fast-moving design team, we needed a tool that matched our pace. From client onboarding to getting paid, this just works clean, fast, and beautifully built."'
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1elq7rn"}
							data-framer-name={"User Info"}
							layoutDependency={layoutDependency}
							layoutId={"LqxuAK_uq"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-15rmbtw"}
								data-framer-name={"Profile Image"}
								layoutDependency={layoutDependency}
								layoutId={"gd9Oy4ttS"}
								style={{
									backgroundColor: "rgb(255, 255, 255)",
									borderBottomLeftRadius: 1e3,
									borderBottomRightRadius: 1e3,
									borderTopLeftRadius: 1e3,
									borderTopRightRadius: 1e3,
								}}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 32 + 167 + 81.5 + 2,
										),
										sizes: "52px",
										...toResponsiveImage(jk3RY9Xr3),
									}}
									className={"framer-1g9jwn2"}
									data-border={true}
									data-framer-name={"Taylor Gibson profile 1"}
									layoutDependency={layoutDependency}
									layoutId={"dLxUnWh7G"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color": "rgb(255, 255, 255)",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								/>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1quf6ma"}
								data-framer-name={"Name + Position"}
								layoutDependency={layoutDependency}
								layoutId={"pLRiQtRkI"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1724lp6"}
									data-framer-name={"Leah Daniel"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"ej3CD2bRV"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={FrWUmwkt3}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1f5jbyr"}
											data-styles-preset={"oM4DrnKwh"}
										>
											<motion.strong suppressHydrationWarning={true}>
												{"Leah Daniel"}
											</motion.strong>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1oa24aa"}
									data-framer-name={"Design Ops Lead, teamwork."}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"NkSYNwI0V"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={BUy0U2_Ht}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1lpqzqx"}
											data-styles-preset={"uwmmbeA4Q"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-12cbeffe-102b-4e11-b76d-26c6823b7d37, rgb(117, 113, 112)))",
											}}
										>
											{"Design Ops Lead, teamwork."}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MxTqP.framer-6ojzk9, .framer-MxTqP .framer-6ojzk9 { display: block; }",
	".framer-MxTqP.framer-1a9oivf { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 32px; position: relative; width: 395px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MxTqP .framer-1mgldnr, .framer-MxTqP .framer-1724lp6, .framer-MxTqP .framer-1oa24aa { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-MxTqP .framer-1elq7rn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-MxTqP .framer-15rmbtw { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 56px); overflow: hidden; position: relative; width: 56px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MxTqP .framer-1g9jwn2 { bottom: 2px; flex: none; left: 2px; position: absolute; right: 2px; top: 2px; }",
	".framer-MxTqP .framer-1quf6ma { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-MxTqP.framer-v-1wlegg9.framer-1a9oivf { width: 320px; }",
	...css3,
	...css,
	...css2,
	'.framer-MxTqP[data-border="true"]::after, .framer-MxTqP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerugDauJtmh = withCSS(Component, css4, "framer-MxTqP");
var stdin_default = FramerugDauJtmh;
FramerugDauJtmh.displayName = "Reviews Card";
FramerugDauJtmh.defaultProps = {
	height: 287,
	width: 395,
};
addPropertyControls(FramerugDauJtmh, {
	variant: {
		options: ["jpA_HH3dp", "NFPD0u5mY"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	K3T_HZ6vw: {
		defaultValue:
			'"As a fast-moving design team, we needed a tool that matched our pace. From client onboarding to getting paid, this just works clean, fast, and beautifully built."',
		displayTextArea: false,
		title: "Content",
		type: ControlType.String,
	},
	jk3RY9Xr3: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	FrWUmwkt3: {
		defaultValue: "Leah Daniel",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	BUy0U2_Ht: {
		defaultValue: "Design Ops Lead, teamwork.",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
});
addFonts(
	FramerugDauJtmh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:reviews-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ReviewsCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1c5ad012f0be715452c68f8b3c49d52555e3ae5551244a1f9b7ed7d67faf3a9d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var reviews_card_default = ComponentWithRoot;
export { reviews_card_default as default };
